# Copyright 2021-2026 MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""headneck_muscles — 23-entry SNOMED table for the `headneck_muscles` task (Phase 22, plan 22-02).

Generated by the throwaway 22-02 script /raid/tmp/22_gen_modules.py (run with
the app venv) from:
  * TS 2.18.0 `resources/totalsegmentator_snomed_mapping.csv` — category/type
    codes VERBATIM for every mapped label (no editing, no re-derivation).
    CSV-mapped: 0/23.
  * TS 2.18.0 `dicom_io.py:532-567` — the generic fallback for unmapped
    labels (SCT Tissue 85756007 for BOTH category and type, no property
    codes invented). Unmapped here: sternocleidomastoid_right, sternocleidomastoid_left, superior_pharyngeal_constrictor, middle_pharyngeal_constrictor, inferior_pharyngeal_constrictor, trapezius_right, trapezius_left, platysma_right, platysma_left, levator_scapulae_right, levator_scapulae_left, anterior_scalene_right, anterior_scalene_left, middle_scalene_right, middle_scalene_left, posterior_scalene_right, posterior_scalene_left, sterno_thyroid_right, sterno_thyroid_left, thyrohyoid_right, thyrohyoid_left, prevertebral_right, prevertebral_left.  # noqa: B950
  * TS `dicom_io.py` emits the registry class NAME as the segment label and
    a per-run random display color for unmapped labels; this app's
    SegmentDescription class has NO display-color field, so the color half of
    the TS fallback is inexpressible and intentionally unused (only the
    code-fallback half is portable, and that is what this table carries).

Entry order is label id 1..23 (the SEG writer assigns SegmentNumber =
index + 1 — dicom_seg_writer_operator.py:239 contract). Consumed by app.py
via the registry `snomed` attribute (importlib + getattr — no hard-coded
module name in app.py).
Weights: Dataset778/779 v2.3.0-weights (TS 2.18). 0/23 CSV-mapped — the whole
table is the generic Tissue/Tissue fallback, which is exactly what TS 2.18
itself emits for these labels (no codes invented).

"""

# required for setting SegmentDescription attributes
# direct import as this is not part of App SDK package
from pydicom.sr.codedict import codes
from pydicom.sr.coding import Code

try:  # package-style import (my_app.*)
    from my_app.dicom_seg_writer_operator import SegmentDescription
except ImportError:  # flat import (my_app dir on sys.path, as the app runner provides)
    from dicom_seg_writer_operator import SegmentDescription

# general algorithm information
_headneck_muscles_algorithm_name = "CT TotalSegmentator Headneck Muscles Segmentation"
_headneck_muscles_algorithm_family = codes.DCM.ArtificialIntelligence
_headneck_muscles_algorithm_version = "2.18.0"

__all__ = [
    "headneck_muscles_descriptions",
    "headneck_muscles_volume_labels",
    "headneck_muscles_algorithm_name",
    "headneck_muscles_algorithm_family",
    "headneck_muscles_algorithm_version",
]

headneck_muscles_descriptions = [
    SegmentDescription(
        segment_label="sternocleidomastoid_right",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="sternocleidomastoid_left",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="superior_pharyngeal_constrictor",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="middle_pharyngeal_constrictor",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="inferior_pharyngeal_constrictor",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="trapezius_right",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="trapezius_left",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="platysma_right",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="platysma_left",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="levator_scapulae_right",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="levator_scapulae_left",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="anterior_scalene_right",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="anterior_scalene_left",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="middle_scalene_right",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="middle_scalene_left",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="posterior_scalene_right",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="posterior_scalene_left",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="sterno_thyroid_right",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="sterno_thyroid_left",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="thyrohyoid_right",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="thyrohyoid_left",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="prevertebral_right",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
    SegmentDescription(
        segment_label="prevertebral_left",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_headneck_muscles_algorithm_name,
        algorithm_family=_headneck_muscles_algorithm_family,
        algorithm_version=_headneck_muscles_algorithm_version,
    ),
]

# define labels for custom volume transforms (no "background")
headneck_muscles_volume_labels = {
    "sternocleidomastoid_right": 1,
    "sternocleidomastoid_left": 2,
    "superior_pharyngeal_constrictor": 3,
    "middle_pharyngeal_constrictor": 4,
    "inferior_pharyngeal_constrictor": 5,
    "trapezius_right": 6,
    "trapezius_left": 7,
    "platysma_right": 8,
    "platysma_left": 9,
    "levator_scapulae_right": 10,
    "levator_scapulae_left": 11,
    "anterior_scalene_right": 12,
    "anterior_scalene_left": 13,
    "middle_scalene_right": 14,
    "middle_scalene_left": 15,
    "posterior_scalene_right": 16,
    "posterior_scalene_left": 17,
    "sterno_thyroid_right": 18,
    "sterno_thyroid_left": 19,
    "thyrohyoid_right": 20,
    "thyrohyoid_left": 21,
    "prevertebral_right": 22,
    "prevertebral_left": 23,
}

# ModelInfo fields for the P10 output chain (app.py resolves them from this
# module via the registry `snomed` attribute — getattr, no hard-coded names)
headneck_muscles_algorithm_name = _headneck_muscles_algorithm_name
headneck_muscles_algorithm_family = _headneck_muscles_algorithm_family
headneck_muscles_algorithm_version = _headneck_muscles_algorithm_version
