# Copyright 2021-2026 MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# due to the large # of segmented organs (117) for this model, segment descriptions
# are defined here as to not pollute app.py

# custom DICOMSegmentationWriterOperator
from dicom_seg_writer_operator import SegmentDescription

# required for setting SegmentDescription attributes
# direct import as this is not part of App SDK package
from pydicom.sr.codedict import codes
from pydicom.sr.coding import Code

# segment labels, property categories, property types, and property type modifiers
# were pulled from the TotalSegmentator SNOMED Mapping:
# https://github.com/wasserth/TotalSegmentator/blob/master/totalsegmentator/resources/totalsegmentator_snomed_mapping.csv

# the SNOMED CT Browser was used as a source for creating existing codes that are not present in pydicom.sr.codedict:
# https://browser.ihtsdotools.org/?perspective=full&conceptId1=404684003&edition=MAIN/2026-05-01&release=&languages=en

# property type modifiers are not supported in the MONAI SegmentDescription class
# relevant segmented_property_type_modifier_code added, but commented out

# per pydicom.sr.dict, there are multiple SCTIDs (code values) for AnatomicalStructure: 123037004 and 91723000
# this causes codedict.py to throw a RuntimeError; will use BodyStructure instead
# per SNOMED CT Browser, BodyStructure has SCTID 123037004; AnatomicalStructure has SCTID 91723000

# create the required segment description for each segment with
# the actual algorithm and the pertinent organ/tissue; the segment_label, algorithm_name,
# and algorithm_version are of DICOM VR LO type, limited to 64 chars
# https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_6.2.html

# general algorithm information
_algorithm_name = "CT TotalSegmentator Segmentation"
_algorithm_family = codes.DCM.ArtificialIntelligence
_algorithm_version = (
    "2.14.0"  # weights pulled from PyPi TotalSegmentator==2.14.0; unclear if weights 2.5.0 on GitHub is latest
)

ai_segment_descriptions = [
    SegmentDescription(
        segment_label="Spleen",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Spleen,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Kidney",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Kidney,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Kidney",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Kidney,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Gallbladder",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Gallbladder,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Liver",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Liver,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Stomach",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Stomach,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Pancreas",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Pancreas,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Adrenal Gland",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.AdrenalGland,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Adrenal Gland",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.AdrenalGland,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Lung Upper Lobe",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.UpperLobeOfLung,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Lung Lower Lobe",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.LowerLobeOfLung,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Lung Upper Lobe",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.UpperLobeOfLung,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Lung Middle Lobe",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.MiddleLobeOfRightLung,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Lung Lower Lobe",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.LowerLobeOfLung,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Esophagus",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Esophagus,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Trachea",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Trachea,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Thyroid",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Thyroid,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Small Bowel",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.SmallIntestine,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Duodenum",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Duodenum,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Colon",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Colon,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Urinary Bladder",
        segmented_property_category=codes.SCT.BodyStructure,
        # 89837001 corresponds to Bladder and UrinaryBladderStructure
        # SNOMED CT Browser has the latter as Preferred
        segmented_property_type=codes.SCT.UrinaryBladderStructure,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Prostate",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Prostate,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Kidney Cyst",
        # MorphologicallyAlteredStructure not available in SCT codes
        segmented_property_category=codes.SCT.MorphologicallyAbnormalStructure,
        segmented_property_type=codes.SCT.Cyst,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Kidney Cyst",
        # MorphologicallyAlteredStructure not available in SCT codes
        segmented_property_category=codes.SCT.MorphologicallyAbnormalStructure,
        segmented_property_type=codes.SCT.Cyst,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Sacrum",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Sacrum,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="S1 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="181846009", scheme_designator="SCT", meaning="Entire S1 vertebra"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="L5 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="49668003", scheme_designator="SCT", meaning="Bone structure of L5"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="L4 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="11994002", scheme_designator="SCT", meaning="Bone structure of L4"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="L3 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="36470004", scheme_designator="SCT", meaning="Bone structure of L3"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="L2 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="14293000", scheme_designator="SCT", meaning="Bone structure of L2"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="L1 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="66794005", scheme_designator="SCT", meaning="Bone structure of L1"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T12 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="23215003", scheme_designator="SCT", meaning="Bone structure of T12"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T11 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="12989004", scheme_designator="SCT", meaning="Bone structure of T11"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T10 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="7610001", scheme_designator="SCT", meaning="Bone structure of T10"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T9 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="82687006", scheme_designator="SCT", meaning="Bone structure of T9"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T8 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="11068009", scheme_designator="SCT", meaning="Bone structure of T8"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T7 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="62487009", scheme_designator="SCT", meaning="Bone structure of T7"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T6 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="45296009", scheme_designator="SCT", meaning="Bone structure of T6"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T5 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="56401006", scheme_designator="SCT", meaning="Bone structure of T5"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T4 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="73071006", scheme_designator="SCT", meaning="Bone structure of T4"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T3 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="1626008", scheme_designator="SCT", meaning="Bone structure of T3"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T2 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="53733008", scheme_designator="SCT", meaning="Bone structure of T2"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T1 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="64864005", scheme_designator="SCT", meaning="Bone structure of T1"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="C7 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="87391001", scheme_designator="SCT", meaning="Bone structure of C7"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="C6 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="36054005", scheme_designator="SCT", meaning="Bone structure of C6"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="C5 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="36978003", scheme_designator="SCT", meaning="Bone structure of C5"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="C4 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="5329002", scheme_designator="SCT", meaning="Bone structure of C4"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="C3 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="113205007", scheme_designator="SCT", meaning="Bone structure of C3"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="C2 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="39976000", scheme_designator="SCT", meaning="Bone structure of axis"),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="C1 Vertebra",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.C1Vertebra,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Heart",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Heart,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Aorta",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Aorta,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Pulmonary Vein",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.PulmonaryVein,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Brachiocephalic Trunk",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.BrachiocephalicTrunk,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Subclavian Artery",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.SubclavianArtery,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Subclavian Artery",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.SubclavianArtery,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Common Carotid Artery",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.CommonCarotidArtery,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Common Carotid Artery",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.CommonCarotidArtery,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Brachiocephalic Vein",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.BrachiocephalicVein,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Brachiocephalic Vein",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.BrachiocephalicVein,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Atrial Appendage",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.LeftAuricularAppendage,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Superior Vena Cava",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.SuperiorVenaCava,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Inferior Vena Cava",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.InferiorVenaCava,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Portal Vein and Splenic Vein",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(
            value="110765007", scheme_designator="SCT", meaning="Portal vein and splenic vein, CS"
        ),
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Iliac Artery",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.CommonIliacArtery,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Iliac Artery",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.CommonIliacArtery,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Iliac Vein",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.CommonIliacVein,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Iliac Vein",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.CommonIliacVein,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Humerus",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Humerus,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Humerus",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Humerus,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Scapula",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Scapula,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Scapula",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Scapula,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Clavicle",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Clavicle,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Clavicle",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Clavicle,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Femur",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Femur,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Femur",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Femur,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Hip",
        segmented_property_category=codes.SCT.BodyStructure,
        # 29836001 corresponds to HipJoint and HipRegionStructure; latter is more accurate
        segmented_property_type=codes.SCT.HipRegionStructure,
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Hip",
        segmented_property_category=codes.SCT.BodyStructure,
        # 29836001 corresponds to HipJoint and HipRegionStructure; latter is more accurate
        segmented_property_type=codes.SCT.HipRegionStructure,
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Spinal Cord",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.SpinalCord,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Gluteus Maximus",
        segmented_property_category=codes.SCT.BodyStructure,
        # changed from TotalSegmentator; 181674001 is Entire gluteus maximus muscle
        segmented_property_type=Code(
            value="206007", scheme_designator="SCT", meaning="Structure of gluteus maximus muscle"
        ),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Gluteus Maximus",
        segmented_property_category=codes.SCT.BodyStructure,
        # changed from TotalSegmentator; 181674001 is Entire gluteus maximus muscle
        segmented_property_type=Code(
            value="206007", scheme_designator="SCT", meaning="Structure of gluteus maximus muscle"
        ),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Gluteus Medius",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(
            value="78333006", scheme_designator="SCT", meaning="Structure of gluteus medius muscle"
        ),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Gluteus Medius",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(
            value="78333006", scheme_designator="SCT", meaning="Structure of gluteus medius muscle"
        ),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Gluteus Minimus",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(
            value="75297007", scheme_designator="SCT", meaning="Structure of gluteus minimus muscle"
        ),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Gluteus Minimus",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(
            value="75297007", scheme_designator="SCT", meaning="Structure of gluteus minimus muscle"
        ),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Autochthon",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="244849004", scheme_designator="SCT", meaning="Deep muscle of back"),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Autochthon",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="244849004", scheme_designator="SCT", meaning="Deep muscle of back"),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Iliopsoas",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(
            value="68455001", scheme_designator="SCT", meaning="Structure of iliopsoas muscle"
        ),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Iliopsoas",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(
            value="68455001", scheme_designator="SCT", meaning="Structure of iliopsoas muscle"
        ),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Brain",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Brain,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Skull",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Skull,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 1",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="48535007", scheme_designator="SCT", meaning="Bone structure of first rib"),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 2",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="78247007", scheme_designator="SCT", meaning="Bone structure of second rib"),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 3",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="25888004", scheme_designator="SCT", meaning="Bone structure of third rib"),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 4",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="25523003", scheme_designator="SCT", meaning="Bone structure of fourth rib"),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 5",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="15339008", scheme_designator="SCT", meaning="Bone structure of fifth rib"),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 6",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="59558009", scheme_designator="SCT", meaning="Bone structure of sixth rib"),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 7",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(
            value="24915002", scheme_designator="SCT", meaning="Bone structure of seventh rib"
        ),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 8",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="5953002", scheme_designator="SCT", meaning="Bone structure of eighth rib"),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 9",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="22565002", scheme_designator="SCT", meaning="Bone structure of ninth rib"),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 10",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="77644006", scheme_designator="SCT", meaning="Bone structure of tenth rib"),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 11",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(
            value="58830002", scheme_designator="SCT", meaning="Bone structure of eleventh rib"
        ),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 12",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(
            value="43993008", scheme_designator="SCT", meaning="Bone structure of twelfth rib"
        ),
        # segmented_property_type_modifier_code=codes.SCT.Left,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 1",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="48535007", scheme_designator="SCT", meaning="Bone structure of first rib"),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 2",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="78247007", scheme_designator="SCT", meaning="Bone structure of second rib"),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 3",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="25888004", scheme_designator="SCT", meaning="Bone structure of third rib"),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 4",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="25523003", scheme_designator="SCT", meaning="Bone structure of fourth rib"),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 5",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="15339008", scheme_designator="SCT", meaning="Bone structure of fifth rib"),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 6",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="59558009", scheme_designator="SCT", meaning="Bone structure of sixth rib"),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 7",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(
            value="24915002", scheme_designator="SCT", meaning="Bone structure of seventh rib"
        ),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 8",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="5953002", scheme_designator="SCT", meaning="Bone structure of eighth rib"),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 9",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="22565002", scheme_designator="SCT", meaning="Bone structure of ninth rib"),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 10",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(value="77644006", scheme_designator="SCT", meaning="Bone structure of tenth rib"),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 11",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(
            value="58830002", scheme_designator="SCT", meaning="Bone structure of eleventh rib"
        ),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 12",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=Code(
            value="43993008", scheme_designator="SCT", meaning="Bone structure of twelfth rib"
        ),
        # segmented_property_type_modifier_code=codes.SCT.Right,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Sternum",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.Sternum,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Costal Cartilages",
        segmented_property_category=codes.SCT.BodyStructure,
        segmented_property_type=codes.SCT.CostalCartilage,
        algorithm_name=_algorithm_name,
        algorithm_family=_algorithm_family,
        algorithm_version=_algorithm_version,
    ),
]

# 26-04: organs-subset description table for the dev layout-test tasks
# (organs_lowres_test / organs_cascade_test — organs part only, local labels
# 1..24). The full table above is ordered by total-task label id 1..117 with
# labels 1..24 = the 24 organs, so the first 24 entries are exactly the
# organs descriptions in label order. Pure data slice; the full table is
# untouched (total task unaffected).
organs_descriptions = ai_segment_descriptions[:24]

# define labels for custom volume transforms
# abbreviated in some cases to not exceed VR SH max length of 16
volume_labels = {
    "background": 0,
    "spleen": 1,
    "r.kidney": 2,
    "l.kidney": 3,
    "gallbladder": 4,
    "liver": 5,
    "stomach": 6,
    "pancreas": 7,
    "r.adrnl.glnd": 8,
    "l.adrnl.glnd": 9,
    "l.lng.up.lb": 10,
    "l.lng.low.lb": 11,
    "r.lng.up.lb": 12,
    "r.lng.mid.lb": 13,
    "r.lng.low.lb": 14,
    "esophagus": 15,
    "trachea": 16,
    "thyroid": 17,
    "small.bowel": 18,
    "duodenum": 19,
    "colon": 20,
    "urinry.blddr": 21,
    "prostate": 22,
    "l.kid.cyst": 23,
    "r.kid.cyst": 24,
    "sacrum": 25,
    "s1.vrtbrae": 26,
    "l5.vrtbrae": 27,
    "l4.vrtbrae": 28,
    "l3.vrtbrae": 29,
    "l2.vrtbrae": 30,
    "l1.vrtbrae": 31,
    "t12.vrtbrae": 32,
    "t11.vrtbrae": 33,
    "t10.vrtbrae": 34,
    "t9.vrtbrae": 35,
    "t8.vrtbrae": 36,
    "t7.vrtbrae": 37,
    "t6.vrtbrae": 38,
    "t5.vrtbrae": 39,
    "t4.vrtbrae": 40,
    "t3.vrtbrae": 41,
    "t2.vrtbrae": 42,
    "t1.vrtbrae": 43,
    "c7.vrtbrae": 44,
    "c6.vrtbrae": 45,
    "c5.vrtbrae": 46,
    "c4.vrtbrae": 47,
    "c3.vrtbrae": 48,
    "c2.vrtbrae": 49,
    "c1.vrtbrae": 50,
    "heart": 51,
    "aorta": 52,
    "pulm.vein": 53,
    "brchcph.trnk": 54,
    "r.subclv.art": 55,
    "l.subclv.art": 56,
    "r.ccarot.art": 57,
    "l.ccarot.art": 58,
    "l.brchcp.vn": 59,
    "r.brchcp.vn": 60,
    "l.atr.append": 61,
    "sup.ven.cava": 62,
    "inf.ven.cava": 63,
    "prtl.spln.vn": 64,
    "l.iliac.art": 65,
    "r.iliac.art": 66,
    "l.iliac.vein": 67,
    "r.iliac.vein": 68,
    "l.humerus": 69,
    "r.humerus": 70,
    "l.scapula": 71,
    "r.scapula": 72,
    "l.clavicle": 73,
    "r.clavicle": 74,
    "l.femur": 75,
    "r.femur": 76,
    "l.hip": 77,
    "r.hip": 78,
    "spinal.cord": 79,
    "l.glut.max": 80,
    "r.glut.max": 81,
    "l.glut.med": 82,
    "r.glut.med": 83,
    "l.glut.min": 84,
    "r.glut.min": 85,
    "l.autochthon": 86,
    "r.autochthon": 87,
    "l.iliopsoas": 88,
    "r.iliopsoas": 89,
    "brain": 90,
    "skull": 91,
    "l.rib.1": 92,
    "l.rib.2": 93,
    "l.rib.3": 94,
    "l.rib.4": 95,
    "l.rib.5": 96,
    "l.rib.6": 97,
    "l.rib.7": 98,
    "l.rib.8": 99,
    "l.rib.9": 100,
    "l.rib.10": 101,
    "l.rib.11": 102,
    "l.rib.12": 103,
    "r.rib.1": 104,
    "r.rib.2": 105,
    "r.rib.3": 106,
    "r.rib.4": 107,
    "r.rib.5": 108,
    "r.rib.6": 109,
    "r.rib.7": 110,
    "r.rib.8": 111,
    "r.rib.9": 112,
    "r.rib.10": 113,
    "r.rib.11": 114,
    "r.rib.12": 115,
    "sternum": 116,
    "cost.cartlg": 117,
}
