# Copyright 2021-2026 MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""total_v3 — 117-entry SNOMED table for the `total_v3` task (Phase 22, plan 22-02).

Generated by the throwaway 22-02 script /raid/tmp/22_gen_modules.py (run with
the app venv) from:
  * TS 2.18.0 `resources/totalsegmentator_snomed_mapping.csv` — category/type
    codes VERBATIM for every mapped label (no editing, no re-derivation).
    CSV-mapped: 116/117.
  * TS 2.18.0 `dicom_io.py:532-567` — the generic fallback for unmapped
    labels (SCT Tissue 85756007 for BOTH category and type, no property
    codes invented). Unmapped here: vertebrae_L6.
  * TS `dicom_io.py` emits the registry class NAME as the segment label and
    a per-run random display color for unmapped labels; this app's
    SegmentDescription class has NO display-color field, so the color half of
    the TS fallback is inexpressible and intentionally unused (only the
    code-fallback half is portable, and that is what this table carries).

Entry order is label id 1..117 (the SEG writer assigns SegmentNumber =
index + 1 — dicom_seg_writer_operator.py:239 contract). Consumed by app.py
via the registry `snomed` attribute (importlib + getattr — no hard-coded
module name in app.py).
total_v3 shares the total 5-part geometry (117 unified labels); entry 26 is
renamed vertebrae_L6 (registry label 26 — TS 2.18 `class_map["total_v3"][26]`) and
carries the generic fallback because vertebrae_L6 has no CSV row. The other
116 entries reuse the committed `total` table's names/codes exactly (module
ai_segment_descriptions.py). Weights: v3.0.0-weights (TS 2.18).

"""

# required for setting SegmentDescription attributes
# direct import as this is not part of App SDK package
from pydicom.sr.codedict import codes
from pydicom.sr.coding import Code

try:  # package-style import (my_app.*)
    from my_app.dicom_seg_writer_operator import SegmentDescription
except ImportError:  # flat import (my_app dir on sys.path, as the app runner provides)
    from dicom_seg_writer_operator import SegmentDescription

# general algorithm information
_total_v3_algorithm_name = "CT TotalSegmentator Segmentation"
_total_v3_algorithm_family = codes.DCM.ArtificialIntelligence
_total_v3_algorithm_version = "2.18.0"

__all__ = [
    "total_v3_descriptions",
    "total_v3_volume_labels",
    "total_v3_algorithm_name",
    "total_v3_algorithm_family",
    "total_v3_algorithm_version",
]

total_v3_descriptions = [
    SegmentDescription(
        segment_label="Spleen",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="78961009",
            scheme_designator="SCT",
            meaning="Spleen",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Kidney",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="64033007",
            scheme_designator="SCT",
            meaning="Kidney",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Kidney",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="64033007",
            scheme_designator="SCT",
            meaning="Kidney",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Gallbladder",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="28231008",
            scheme_designator="SCT",
            meaning="Gallbladder",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Liver",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="10200004",
            scheme_designator="SCT",
            meaning="Liver",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Stomach",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="69695003",
            scheme_designator="SCT",
            meaning="Stomach",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Pancreas",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="15776009",
            scheme_designator="SCT",
            meaning="Pancreas",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Adrenal Gland",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="23451007",
            scheme_designator="SCT",
            meaning="Adrenal gland",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Adrenal Gland",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="23451007",
            scheme_designator="SCT",
            meaning="Adrenal gland",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Lung Upper Lobe",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="45653009",
            scheme_designator="SCT",
            meaning="Upper lobe of lung",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Lung Lower Lobe",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="90572001",
            scheme_designator="SCT",
            meaning="Lower lobe of lung",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Lung Upper Lobe",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="45653009",
            scheme_designator="SCT",
            meaning="Upper lobe of lung",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Lung Middle Lobe",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="72481006",
            scheme_designator="SCT",
            meaning="Middle lobe of right lung",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Lung Lower Lobe",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="90572001",
            scheme_designator="SCT",
            meaning="Lower lobe of lung",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Esophagus",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="32849002",
            scheme_designator="SCT",
            meaning="Esophagus",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Trachea",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="44567001",
            scheme_designator="SCT",
            meaning="Trachea",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Thyroid",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="69748006",
            scheme_designator="SCT",
            meaning="Thyroid",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Small Bowel",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="30315005",
            scheme_designator="SCT",
            meaning="Small intestine",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Duodenum",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="38848004",
            scheme_designator="SCT",
            meaning="Duodenum",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Colon",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="71854001",
            scheme_designator="SCT",
            meaning="Colon",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Urinary Bladder",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="89837001",
            scheme_designator="SCT",
            meaning="Urinary bladder structure (body structure)",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Prostate",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="41216001",
            scheme_designator="SCT",
            meaning="Prostate",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Kidney Cyst",
        segmented_property_category=Code(
            value="49755003",
            scheme_designator="SCT",
            meaning="Morphologically Abnormal Structure",
        ),
        segmented_property_type=Code(
            value="367643001",
            scheme_designator="SCT",
            meaning="Cyst",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Kidney Cyst",
        segmented_property_category=Code(
            value="49755003",
            scheme_designator="SCT",
            meaning="Morphologically Abnormal Structure",
        ),
        segmented_property_type=Code(
            value="367643001",
            scheme_designator="SCT",
            meaning="Cyst",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Sacrum",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="54735007",
            scheme_designator="SCT",
            meaning="Sacrum",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_L6",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="L5 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="49668003",
            scheme_designator="SCT",
            meaning="Bone structure of L5",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="L4 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="11994002",
            scheme_designator="SCT",
            meaning="Bone structure of L4",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="L3 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="36470004",
            scheme_designator="SCT",
            meaning="Bone structure of L3",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="L2 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="14293000",
            scheme_designator="SCT",
            meaning="Bone structure of L2",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="L1 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="66794005",
            scheme_designator="SCT",
            meaning="Bone structure of L1",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T12 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="23215003",
            scheme_designator="SCT",
            meaning="Bone structure of T12",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T11 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="12989004",
            scheme_designator="SCT",
            meaning="Bone structure of T11",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T10 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="7610001",
            scheme_designator="SCT",
            meaning="Bone structure of T10",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T9 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="82687006",
            scheme_designator="SCT",
            meaning="Bone structure of T9",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T8 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="11068009",
            scheme_designator="SCT",
            meaning="Bone structure of T8",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T7 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="62487009",
            scheme_designator="SCT",
            meaning="Bone structure of T7",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T6 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="45296009",
            scheme_designator="SCT",
            meaning="Bone structure of T6",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T5 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="56401006",
            scheme_designator="SCT",
            meaning="Bone structure of T5",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T4 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="73071006",
            scheme_designator="SCT",
            meaning="Bone structure of T4",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T3 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="1626008",
            scheme_designator="SCT",
            meaning="Bone structure of T3",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T2 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="53733008",
            scheme_designator="SCT",
            meaning="Bone structure of T2",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="T1 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="64864005",
            scheme_designator="SCT",
            meaning="Bone structure of T1",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="C7 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="87391001",
            scheme_designator="SCT",
            meaning="Bone structure of C7",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="C6 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="36054005",
            scheme_designator="SCT",
            meaning="Bone structure of C6",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="C5 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="36978003",
            scheme_designator="SCT",
            meaning="Bone structure of C5",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="C4 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="5329002",
            scheme_designator="SCT",
            meaning="Bone structure of C4",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="C3 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="113205007",
            scheme_designator="SCT",
            meaning="Bone structure of C3",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="C2 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="39976000",
            scheme_designator="SCT",
            meaning="Bone structure of axis",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="C1 Vertebra",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="14806007",
            scheme_designator="SCT",
            meaning="C1 vertebra",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Heart",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="80891009",
            scheme_designator="SCT",
            meaning="Heart",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Aorta",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="15825003",
            scheme_designator="SCT",
            meaning="Aorta",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Pulmonary Vein",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="122972007",
            scheme_designator="SCT",
            meaning="Pulmonary vein",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Brachiocephalic Trunk",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="12691009",
            scheme_designator="SCT",
            meaning="brachiocephalic trunk",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Subclavian Artery",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="36765005",
            scheme_designator="SCT",
            meaning="Subclavian artery",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Subclavian Artery",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="36765005",
            scheme_designator="SCT",
            meaning="Subclavian artery",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Common Carotid Artery",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="32062004",
            scheme_designator="SCT",
            meaning="Common carotid artery",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Common Carotid Artery",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="32062004",
            scheme_designator="SCT",
            meaning="Common carotid artery",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Brachiocephalic Vein",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="8887007",
            scheme_designator="SCT",
            meaning="Brachiocephalic vein",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Brachiocephalic Vein",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="8887007",
            scheme_designator="SCT",
            meaning="Brachiocephalic vein",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Atrial Appendage",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="33626005",
            scheme_designator="SCT",
            meaning="Left auricular appendage",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Superior Vena Cava",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="48345005",
            scheme_designator="SCT",
            meaning="Superior vena cava",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Inferior Vena Cava",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="64131007",
            scheme_designator="SCT",
            meaning="Inferior vena cava",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Portal Vein and Splenic Vein",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="110765007",
            scheme_designator="SCT",
            meaning="Portal vein and splenic vein, CS",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Iliac Artery",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="73634005",
            scheme_designator="SCT",
            meaning="Common iliac artery",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Iliac Artery",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="73634005",
            scheme_designator="SCT",
            meaning="Common iliac artery",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Iliac Vein",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="46027005",
            scheme_designator="SCT",
            meaning="Common iliac vein",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Iliac Vein",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="46027005",
            scheme_designator="SCT",
            meaning="Common iliac vein",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Humerus",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="85050009",
            scheme_designator="SCT",
            meaning="Humerus",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Humerus",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="85050009",
            scheme_designator="SCT",
            meaning="Humerus",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Scapula",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="79601000",
            scheme_designator="SCT",
            meaning="Scapula",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Scapula",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="79601000",
            scheme_designator="SCT",
            meaning="Scapula",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Clavicle",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="51299004",
            scheme_designator="SCT",
            meaning="Clavicle",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Clavicle",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="51299004",
            scheme_designator="SCT",
            meaning="Clavicle",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Femur",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="71341001",
            scheme_designator="SCT",
            meaning="Femur",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Femur",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="71341001",
            scheme_designator="SCT",
            meaning="Femur",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Hip",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="29836001",
            scheme_designator="SCT",
            meaning="Hip region structure (body structure)",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Hip",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="29836001",
            scheme_designator="SCT",
            meaning="Hip region structure (body structure)",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Spinal Cord",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="2748008",
            scheme_designator="SCT",
            meaning="Spinal cord",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Gluteus Maximus",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="206007",
            scheme_designator="SCT",
            meaning="Structure of gluteus maximus muscle",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Gluteus Maximus",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="206007",
            scheme_designator="SCT",
            meaning="Structure of gluteus maximus muscle",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Gluteus Medius",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="78333006",
            scheme_designator="SCT",
            meaning="Structure of gluteus medius muscle",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Gluteus Medius",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="78333006",
            scheme_designator="SCT",
            meaning="Structure of gluteus medius muscle",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Gluteus Minimus",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="75297007",
            scheme_designator="SCT",
            meaning="Structure of gluteus minimus muscle",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Gluteus Minimus",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="75297007",
            scheme_designator="SCT",
            meaning="Structure of gluteus minimus muscle",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Autochthon",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="244849004",
            scheme_designator="SCT",
            meaning="Deep muscle of back",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Autochthon",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="244849004",
            scheme_designator="SCT",
            meaning="Deep muscle of back",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Iliopsoas",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="68455001",
            scheme_designator="SCT",
            meaning="Structure of iliopsoas muscle",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Iliopsoas",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="68455001",
            scheme_designator="SCT",
            meaning="Structure of iliopsoas muscle",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Brain",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="12738006",
            scheme_designator="SCT",
            meaning="Brain",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Skull",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="89546000",
            scheme_designator="SCT",
            meaning="Skull",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 1",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="48535007",
            scheme_designator="SCT",
            meaning="Bone structure of first rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 2",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="78247007",
            scheme_designator="SCT",
            meaning="Bone structure of second rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 3",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="25888004",
            scheme_designator="SCT",
            meaning="Bone structure of third rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 4",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="25523003",
            scheme_designator="SCT",
            meaning="Bone structure of fourth rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 5",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="15339008",
            scheme_designator="SCT",
            meaning="Bone structure of fifth rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 6",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="59558009",
            scheme_designator="SCT",
            meaning="Bone structure of sixth rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 7",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="24915002",
            scheme_designator="SCT",
            meaning="Bone structure of seventh rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 8",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="5953002",
            scheme_designator="SCT",
            meaning="Bone structure of eighth rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 9",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="22565002",
            scheme_designator="SCT",
            meaning="Bone structure of ninth rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 10",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="77644006",
            scheme_designator="SCT",
            meaning="Bone structure of tenth rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 11",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="58830002",
            scheme_designator="SCT",
            meaning="Bone structure of eleventh rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Left Rib 12",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="43993008",
            scheme_designator="SCT",
            meaning="Bone structure of twelfth rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 1",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="48535007",
            scheme_designator="SCT",
            meaning="Bone structure of first rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 2",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="78247007",
            scheme_designator="SCT",
            meaning="Bone structure of second rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 3",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="25888004",
            scheme_designator="SCT",
            meaning="Bone structure of third rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 4",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="25523003",
            scheme_designator="SCT",
            meaning="Bone structure of fourth rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 5",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="15339008",
            scheme_designator="SCT",
            meaning="Bone structure of fifth rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 6",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="59558009",
            scheme_designator="SCT",
            meaning="Bone structure of sixth rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 7",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="24915002",
            scheme_designator="SCT",
            meaning="Bone structure of seventh rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 8",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="5953002",
            scheme_designator="SCT",
            meaning="Bone structure of eighth rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 9",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="22565002",
            scheme_designator="SCT",
            meaning="Bone structure of ninth rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 10",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="77644006",
            scheme_designator="SCT",
            meaning="Bone structure of tenth rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 11",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="58830002",
            scheme_designator="SCT",
            meaning="Bone structure of eleventh rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Right Rib 12",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="43993008",
            scheme_designator="SCT",
            meaning="Bone structure of twelfth rib",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Sternum",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="56873002",
            scheme_designator="SCT",
            meaning="Sternum",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
    SegmentDescription(
        segment_label="Costal Cartilages",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Body structure (body structure)",
        ),
        segmented_property_type=Code(
            value="50016007",
            scheme_designator="SCT",
            meaning="Costal Cartilage",
        ),
        algorithm_name=_total_v3_algorithm_name,
        algorithm_family=_total_v3_algorithm_family,
        algorithm_version=_total_v3_algorithm_version,
    ),
]

# define labels for custom volume transforms (no "background")
total_v3_volume_labels = {
    "spleen": 1,
    "kidney_right": 2,
    "kidney_left": 3,
    "gallbladder": 4,
    "liver": 5,
    "stomach": 6,
    "pancreas": 7,
    "adrenal_gland_right": 8,
    "adrenal_gland_left": 9,
    "lung_upper_lobe_left": 10,
    "lung_lower_lobe_left": 11,
    "lung_upper_lobe_right": 12,
    "lung_middle_lobe_right": 13,
    "lung_lower_lobe_right": 14,
    "esophagus": 15,
    "trachea": 16,
    "thyroid_gland": 17,
    "small_bowel": 18,
    "duodenum": 19,
    "colon": 20,
    "urinary_bladder": 21,
    "prostate": 22,
    "kidney_cyst_left": 23,
    "kidney_cyst_right": 24,
    "sacrum": 25,
    "vertebrae_L6": 26,
    "vertebrae_L5": 27,
    "vertebrae_L4": 28,
    "vertebrae_L3": 29,
    "vertebrae_L2": 30,
    "vertebrae_L1": 31,
    "vertebrae_T12": 32,
    "vertebrae_T11": 33,
    "vertebrae_T10": 34,
    "vertebrae_T9": 35,
    "vertebrae_T8": 36,
    "vertebrae_T7": 37,
    "vertebrae_T6": 38,
    "vertebrae_T5": 39,
    "vertebrae_T4": 40,
    "vertebrae_T3": 41,
    "vertebrae_T2": 42,
    "vertebrae_T1": 43,
    "vertebrae_C7": 44,
    "vertebrae_C6": 45,
    "vertebrae_C5": 46,
    "vertebrae_C4": 47,
    "vertebrae_C3": 48,
    "vertebrae_C2": 49,
    "vertebrae_C1": 50,
    "heart": 51,
    "aorta": 52,
    "pulmonary_vein": 53,
    "brachiocephalic_trunk": 54,
    "subclavian_artery_right": 55,
    "subclavian_artery_left": 56,
    "common_carotid_artery_right": 57,
    "common_carotid_artery_left": 58,
    "brachiocephalic_vein_left": 59,
    "brachiocephalic_vein_right": 60,
    "atrial_appendage_left": 61,
    "superior_vena_cava": 62,
    "inferior_vena_cava": 63,
    "portal_vein_and_splenic_vein": 64,
    "iliac_artery_left": 65,
    "iliac_artery_right": 66,
    "iliac_vena_left": 67,
    "iliac_vena_right": 68,
    "humerus_left": 69,
    "humerus_right": 70,
    "scapula_left": 71,
    "scapula_right": 72,
    "clavicula_left": 73,
    "clavicula_right": 74,
    "femur_left": 75,
    "femur_right": 76,
    "hip_left": 77,
    "hip_right": 78,
    "spinal_cord": 79,
    "gluteus_maximus_left": 80,
    "gluteus_maximus_right": 81,
    "gluteus_medius_left": 82,
    "gluteus_medius_right": 83,
    "gluteus_minimus_left": 84,
    "gluteus_minimus_right": 85,
    "autochthon_left": 86,
    "autochthon_right": 87,
    "iliopsoas_left": 88,
    "iliopsoas_right": 89,
    "brain": 90,
    "skull": 91,
    "rib_left_1": 92,
    "rib_left_2": 93,
    "rib_left_3": 94,
    "rib_left_4": 95,
    "rib_left_5": 96,
    "rib_left_6": 97,
    "rib_left_7": 98,
    "rib_left_8": 99,
    "rib_left_9": 100,
    "rib_left_10": 101,
    "rib_left_11": 102,
    "rib_left_12": 103,
    "rib_right_1": 104,
    "rib_right_2": 105,
    "rib_right_3": 106,
    "rib_right_4": 107,
    "rib_right_5": 108,
    "rib_right_6": 109,
    "rib_right_7": 110,
    "rib_right_8": 111,
    "rib_right_9": 112,
    "rib_right_10": 113,
    "rib_right_11": 114,
    "rib_right_12": 115,
    "sternum": 116,
    "costal_cartilages": 117,
}

# ModelInfo fields for the P10 output chain (app.py resolves them from this
# module via the registry `snomed` attribute — getattr, no hard-coded names)
total_v3_algorithm_name = _total_v3_algorithm_name
total_v3_algorithm_family = _total_v3_algorithm_family
total_v3_algorithm_version = _total_v3_algorithm_version
