# Copyright 2021-2026 MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""trunk_cavities — 4-entry SNOMED table for the `trunk_cavities` task (Phase 22, plan 22-02).

Generated by the throwaway 22-02 script /raid/tmp/22_gen_modules.py (run with
the app venv) from:
  * TS 2.18.0 `resources/totalsegmentator_snomed_mapping.csv` — category/type
    codes VERBATIM for every mapped label (no editing, no re-derivation).
    CSV-mapped: 0/4.
  * TS 2.18.0 `dicom_io.py:532-567` — the generic fallback for unmapped
    labels (SCT Tissue 85756007 for BOTH category and type, no property
    codes invented). Unmapped here: abdominal_cavity, thoracic_cavity, pericardium, mediastinum.
  * TS `dicom_io.py` emits the registry class NAME as the segment label and
    a per-run random display color for unmapped labels; this app's
    SegmentDescription class has NO display-color field, so the color half of
    the TS fallback is inexpressible and intentionally unused (only the
    code-fallback half is portable, and that is what this table carries).

Entry order is label id 1..4 (the SEG writer assigns SegmentNumber =
index + 1 — dicom_seg_writer_operator.py:239 contract). Consumed by app.py
via the registry `snomed` attribute (importlib + getattr — no hard-coded
module name in app.py).
Weights: Dataset343 v2.5.0-weights (TS 2.18). 0/4 CSV-mapped — the whole
table is the generic Tissue/Tissue fallback (TS emits the same; no codes
invented).

"""

# required for setting SegmentDescription attributes
# direct import as this is not part of App SDK package
from pydicom.sr.codedict import codes
from pydicom.sr.coding import Code

try:  # package-style import (my_app.*)
    from my_app.dicom_seg_writer_operator import SegmentDescription
except ImportError:  # flat import (my_app dir on sys.path, as the app runner provides)
    from dicom_seg_writer_operator import SegmentDescription

# general algorithm information
_trunk_cavities_algorithm_name = "CT TotalSegmentator Trunk Cavities Segmentation"
_trunk_cavities_algorithm_family = codes.DCM.ArtificialIntelligence
_trunk_cavities_algorithm_version = "2.18.0"

__all__ = [
    "trunk_cavities_descriptions",
    "trunk_cavities_volume_labels",
    "trunk_cavities_algorithm_name",
    "trunk_cavities_algorithm_family",
    "trunk_cavities_algorithm_version",
]

trunk_cavities_descriptions = [
    SegmentDescription(
        segment_label="abdominal_cavity",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_trunk_cavities_algorithm_name,
        algorithm_family=_trunk_cavities_algorithm_family,
        algorithm_version=_trunk_cavities_algorithm_version,
    ),
    SegmentDescription(
        segment_label="thoracic_cavity",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_trunk_cavities_algorithm_name,
        algorithm_family=_trunk_cavities_algorithm_family,
        algorithm_version=_trunk_cavities_algorithm_version,
    ),
    SegmentDescription(
        segment_label="pericardium",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_trunk_cavities_algorithm_name,
        algorithm_family=_trunk_cavities_algorithm_family,
        algorithm_version=_trunk_cavities_algorithm_version,
    ),
    SegmentDescription(
        segment_label="mediastinum",
        segmented_property_category=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        segmented_property_type=Code(
            value="85756007",
            scheme_designator="SCT",
            meaning="Tissue",
        ),
        algorithm_name=_trunk_cavities_algorithm_name,
        algorithm_family=_trunk_cavities_algorithm_family,
        algorithm_version=_trunk_cavities_algorithm_version,
    ),
]

# define labels for custom volume transforms (no "background")
trunk_cavities_volume_labels = {
    "abdominal_cavity": 1,
    "thoracic_cavity": 2,
    "pericardium": 3,
    "mediastinum": 4,
}

# ModelInfo fields for the P10 output chain (app.py resolves them from this
# module via the registry `snomed` attribute — getattr, no hard-coded names)
trunk_cavities_algorithm_name = _trunk_cavities_algorithm_name
trunk_cavities_algorithm_family = _trunk_cavities_algorithm_family
trunk_cavities_algorithm_version = _trunk_cavities_algorithm_version
