# Copyright 2021-2026 MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""vertebrae_pp — 24-entry SNOMED table for the `vertebrae_pp` task (Phase 22, plan 22-02).

Generated by the throwaway 22-02 script /raid/tmp/22_gen_modules.py (run with
the app venv) from:
  * TS 2.18.0 `resources/totalsegmentator_snomed_mapping.csv` — category/type
    codes VERBATIM for every mapped label (no editing, no re-derivation).
    CSV-mapped: 24/24.
  * TS 2.18.0 `dicom_io.py:532-567` — the generic fallback for unmapped
    labels (SCT Tissue 85756007 for BOTH category and type, no property
    codes invented). Unmapped here: none.
  * TS `dicom_io.py` emits the registry class NAME as the segment label and
    a per-run random display color for unmapped labels; this app's
    SegmentDescription class has NO display-color field, so the color half of
    the TS fallback is inexpressible and intentionally unused (only the
    code-fallback half is portable, and that is what this table carries).

Entry order is label id 1..24 (the SEG writer assigns SegmentNumber =
index + 1 — dicom_seg_writer_operator.py:239 contract). Consumed by app.py
via the registry `snomed` attribute (importlib + getattr — no hard-coded
module name in app.py).
Weights: Dataset803 v2.5.0-weights (TS 2.18). 24/24 CSV-mapped.

"""

# required for setting SegmentDescription attributes
# direct import as this is not part of App SDK package
from pydicom.sr.codedict import codes
from pydicom.sr.coding import Code

try:  # package-style import (my_app.*)
    from my_app.dicom_seg_writer_operator import SegmentDescription
except ImportError:  # flat import (my_app dir on sys.path, as the app runner provides)
    from dicom_seg_writer_operator import SegmentDescription

# general algorithm information
_vertebrae_pp_algorithm_name = "CT TotalSegmentator Vertebrae Segmentation"
_vertebrae_pp_algorithm_family = codes.DCM.ArtificialIntelligence
_vertebrae_pp_algorithm_version = "2.18.0"

__all__ = [
    "vertebrae_pp_descriptions",
    "vertebrae_pp_volume_labels",
    "vertebrae_pp_algorithm_name",
    "vertebrae_pp_algorithm_family",
    "vertebrae_pp_algorithm_version",
]

vertebrae_pp_descriptions = [
    SegmentDescription(
        segment_label="vertebrae_C1",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="14806007",
            scheme_designator="SCT",
            meaning="C1 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_C2",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="39976000",
            scheme_designator="SCT",
            meaning="C2 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_C3",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="113205007",
            scheme_designator="SCT",
            meaning="C3 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_C4",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="5329002",
            scheme_designator="SCT",
            meaning="C4 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_C5",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="36978003",
            scheme_designator="SCT",
            meaning="C5 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_C6",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="36054005",
            scheme_designator="SCT",
            meaning="C6 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_C7",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="87391001",
            scheme_designator="SCT",
            meaning="C7 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_T1",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="64864005",
            scheme_designator="SCT",
            meaning="T1 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_T2",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="53733008",
            scheme_designator="SCT",
            meaning="T2 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_T3",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="1626008",
            scheme_designator="SCT",
            meaning="T3 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_T4",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="73071006",
            scheme_designator="SCT",
            meaning="T4 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_T5",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="56401006",
            scheme_designator="SCT",
            meaning="T5 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_T6",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="45296009",
            scheme_designator="SCT",
            meaning="T6 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_T7",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="62487009",
            scheme_designator="SCT",
            meaning="T7 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_T8",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="11068009",
            scheme_designator="SCT",
            meaning="T8 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_T9",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="82687006",
            scheme_designator="SCT",
            meaning="T9 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_T10",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="7610001",
            scheme_designator="SCT",
            meaning="T10 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_T11",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="12989004",
            scheme_designator="SCT",
            meaning="T11 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_T12",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="23215003",
            scheme_designator="SCT",
            meaning="T12 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_L1",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="66794005",
            scheme_designator="SCT",
            meaning="L1 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_L2",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="14293000",
            scheme_designator="SCT",
            meaning="L2 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_L3",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="36470004",
            scheme_designator="SCT",
            meaning="L3 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_L4",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="11994002",
            scheme_designator="SCT",
            meaning="L4 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
    SegmentDescription(
        segment_label="vertebrae_L5",
        segmented_property_category=Code(
            value="123037004",
            scheme_designator="SCT",
            meaning="Anatomical Structure",
        ),
        segmented_property_type=Code(
            value="49668003",
            scheme_designator="SCT",
            meaning="L5 vertebra",
        ),
        algorithm_name=_vertebrae_pp_algorithm_name,
        algorithm_family=_vertebrae_pp_algorithm_family,
        algorithm_version=_vertebrae_pp_algorithm_version,
    ),
]

# define labels for custom volume transforms (no "background")
vertebrae_pp_volume_labels = {
    "vertebrae_C1": 1,
    "vertebrae_C2": 2,
    "vertebrae_C3": 3,
    "vertebrae_C4": 4,
    "vertebrae_C5": 5,
    "vertebrae_C6": 6,
    "vertebrae_C7": 7,
    "vertebrae_T1": 8,
    "vertebrae_T2": 9,
    "vertebrae_T3": 10,
    "vertebrae_T4": 11,
    "vertebrae_T5": 12,
    "vertebrae_T6": 13,
    "vertebrae_T7": 14,
    "vertebrae_T8": 15,
    "vertebrae_T9": 16,
    "vertebrae_T10": 17,
    "vertebrae_T11": 18,
    "vertebrae_T12": 19,
    "vertebrae_L1": 20,
    "vertebrae_L2": 21,
    "vertebrae_L3": 22,
    "vertebrae_L4": 23,
    "vertebrae_L5": 24,
}

# ModelInfo fields for the P10 output chain (app.py resolves them from this
# module via the registry `snomed` attribute — getattr, no hard-coded names)
vertebrae_pp_algorithm_name = _vertebrae_pp_algorithm_name
vertebrae_pp_algorithm_family = _vertebrae_pp_algorithm_family
vertebrae_pp_algorithm_version = _vertebrae_pp_algorithm_version
