FROM nvcr.io/nvidia/clara-holoscan/holoscan:v2.1.0-dgpu
RUN pip install --upgrade pip
RUN pip install monai-deploy-app-sdk
RUN pip install transformers
RUN pip install hub
RUN pip install diffusers
RUN pip install torch
RUN pip install pydicom
RUN pip install accelerate
