DEFAULT_DOCKER_FILE_NAME = "dockerfile"
DEFAULT_BASE_IMAGE = "nvcr.io/nvidia/cuda:11.1-runtime-ubuntu20.04"
DEFAULT_WORK_DIR = "/opt/monai/"
DEFAULT_INPUT_DIR = "input/"
DEFAULT_OUTPUT_DIR = "output/"
DEFAULT_MODELS_DIR = "models/"
