
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-24T16:20:37-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0760904a1248ce316ae0237c8a1127ac5673d7f",
 "version": "2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
