"""Task registry for the totalsegmentator-fast app (Phase 17, plan 17-02, TASK-01).

Tasks are DATA, not code. This module is the single source of truth for all
task-level data: which model parts a task runs, in what order, with what label
offsets, what spacing/resample targets, what crop spec, which label table and
SNOMED description table, and which output mode. Adding a task = adding a
``TASK_REGISTRY`` entry + the model bundles on disk — no DAG code changes.

Sub-mode convention: the registry ships ONE entry per task = the
TotalSegmentator 2.18 ``default`` sub-mode (what this app implements). The
``fast``/``fastest`` sub-modes are expressible spacing variants of the same
topology; they are not shipped in v3.0.

Pure-data import rule: this module imports ONLY the Python standard library.
It must remain importable headless in any Python interpreter (no third-party
or app-runtime imports, no model or corpus files). The one-way
dependency is ``my_app.config`` -> ``my_app.task_specs``; the reverse is
forbidden (it would create a cycle and break headless import).

``labels`` convention (per-task label table, TASK-01):
  * ``str``  -> attribute name of the label table in
    ``my_app.ai_segment_descriptions`` (Phase 17 ships exactly one table:
    ``volume_labels``, 117 entries). Consumers/tests resolve it with
    ``getattr``; ``task_specs`` itself NEVER imports that module.
  * ``dict`` -> inline name -> unified-id label table.
  * ``None`` -> the task emits no label table.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional, Tuple, Union

__all__ = [
    "PartSpec",
    "CropSpec",
    "TaskSpec",
    "TASK_REGISTRY",
    "get_task_spec",
    # topology-construction API (plans.py, Phase 17 plan 17-03) — re-exported so
    # `from my_app.task_specs import build_topology, get_task_spec, resolve_part`
    # (the in-compose import in app.py) resolves.
    "CROP_STAGES",
    "TopologyPlan",
    "build_topology",
    "resolve_part",
]


@dataclass(frozen=True)
class PartSpec:
    """One nnUNet model part of a task (one bundle under the task root)."""

    name: str  # model dir name under the task root
    label_offset: int  # added to the part's local labels on merge
    config_name: str = "3d_fullres"  # per-part bundle config dir
    # (3d_fullres_high / 3d_lowres_high for other catalog tasks)
    max_local_label: Optional[int] = None  # None = read from the bundle's dataset.json


@dataclass(frozen=True)
class CropSpec:
    """Crop pre-stage (Phase 18 consumer; Phase 17 = schema + data only).

    Crop composes with any family (single-model or multi-part) — the TS
    catalog proves it (e.g. headneck_muscles = 2-part + 6-label crop).
    """

    source: Optional[str]  # None = TS default crop model; else a TS task NAME
    # (e.g. "craniofacial_structures" — the `teeth` case)
    labels: tuple  # crop label subset, e.g. ("liver",)
    addon: tuple  # per-axis crop padding, e.g. (20, 20, 20)


@dataclass(frozen=True)
class TaskSpec:
    """Pure-data description of one TotalSegmentator task (TS 2.18 default sub-mode)."""

    task_id: object  # TS nnUNet task id or tuple of ids — provenance, not loaded by the app
    family: str  # "single_model" | "multi_part" | "crop_cascade"
    parts: tuple  # tuple[PartSpec, ...]; order IS the later-part-wins merge order (oracle order)
    crop: object  # CropSpec | None (crop composes with any family)
    resample: object  # float | tuple[float, float, float] | None (None = no TS input pre-resample)
    target_spacing: object  # float | tuple — model-spacing target for the preprocess stage
    resample_order: int = 3
    tile_step_size: float = 0.8  # Phase 19 (19-01): generic single-model SlidingWindow
    # step size. TS nnunet.py:568-572 uses 0.8 ONLY for
    # the total family (total/total_v3/total_mr), 0.5 for
    # every other task (e.g. body=299). Default 0.8 keeps
    # the total path byte/behavior-identical.
    trainer: str = ""
    tta: bool = False
    snomed: str = ""  # table attribute name on the descriptions module (total -> "ai_segment_descriptions")
    snomed_module: str = ""  # descriptions module name under my_app/ (total -> "ai_segment_descriptions")
    labels: object = None  # per-task label table: str attr of my_app.ai_segment_descriptions
    # (Phase 17: only "volume_labels"), inline dict[str, int], or None
    output_mode: str = "seg_sr"  # "seg_sr" (DICOM SEG + SR) | "emit_only" (P8 debug path)
    postprocess: tuple = ()  # Phase 19 (19-05): TS-CLI task postprocessing rules,
    # model resolution, PRE-back-resample. Each rule:
    #   ("keep_largest_blob", label_name)  or
    #   ("remove_small_blobs", label_name, size_thr_mm3)
    # Label names resolve against this spec's `labels`
    # table. () = no task postprocessing (total /
    # liver_segments — TS applies none to them).
    # Provenance: TS 2.18 totalsegmentator/nnunet.py:
    # 686-695 (body only). Executed by
    # operators/task_postprocess_operator.py.
    folds: tuple = (0,)  # Phase 21: TS nnUNet fold ids
    # (provenance — the app already loads every
    # fold present in the bundle; (0,1,2,3,4)
    # for aorta_annulus / aortic_dissection /
    # pulmonary_artery_landmarks).
    robust_crop: bool = False  # Phase 21: crop pre-stage uses TS task 297 @
    # 3mm instead of 298 @ 6mm
    # (lung_vessels / liver_lesions /
    # heartchambers_highres; TS python_api.py:397-410).
    remove_outside: tuple = ()  # Phase 21: label names for the TS remove_outside
    # rule (heartchambers_highres:
    # ("heart", "aorta", "inferior_vena_cava")).
    remove_outside_dilation: float = 0.0  # Phase 21: mm dilation for remove_outside
    # (heartchambers_highres: 10.0).
    licensed: bool = False  # Phase 21: requires a commercial TS license;
    # pure registry metadata (14 catalog tasks).


# ---------------------------------------------------------------------------
# Registry — one entry per task = the TS 2.18 `default` sub-mode.
#
# The registry ships ALL 43 distinct TS 2.18 CT tasks: the 3 shipped entries
# plus 40 generated entries (Phase 21, 21-02). The 40 generated entries are
# emitted by .planning/scripts/21_gen_registry.py from the live TS 2.18 oracle
# (run `/tmp/totalseg-venv/bin/python .planning/scripts/21_gen_registry.py
# --emit` to regenerate, `--check` to verify). DO NOT hand-edit generated
# entries — re-run --emit and --check instead.
#
# Generated-entry notes:
#   * `snomed` / `snomed_module`: backfilled for the 5 Phase-22 sampled
#     tasks (total_v3, headneck_muscles, vertebrae_pp,
#     pleural_pericard_effusion, trunk_cavities — Phase 22, plan 22-02);
#     the remaining 35 stay "" until validated (source = TS
#     totalsegmentator_snomed_mapping.csv; codes are never invented).
#   * `headneck_muscles` part names `part1` / `part2` are the Phase-22
#     bundle-placement contract (weights: Dataset778_headneck_muscles_part1_492subj
#     / Dataset779_headneck_muscles_part2_492subj).
#   * The 14 `licensed=True` tasks are pure registry metadata — running them
#     requires a commercial TS license + checkpoints (none are shipped or
#     pre-downloaded in this repo).
#
# Shipped entries (byte-stable; generator output never overwrites them):
#   * "total"          — VERBATIM from my_app/config/__init__.py (MODEL_PARTS /
#     EXPECTED_MAX_LOCAL_LABEL, Phase 7 07-02, verified against the total
#     bundle's dataset.json label tables and the oracle app_total offsets) and
#     the TS 2.18 catalog (17-catalog-completeness.md). test_task_specs.py
#     re-asserts equality against the live constants on every run.
#   * "liver_segments" — Phase 18 (18-01), from the TS 2.18
#     map_tasks_config.py["liver_segments"] entry + the on-disk bundles
#     (18-models-manifest.sha256; verify_liver_models.py).
#   * "body"           — Phase 19 (19-01), from the TS 2.18
#     map_tasks_config.py["body"] entry (task 299, 3d_fullres @ 1.5 iso,
#     resample order 1, step size 0.5, no crop/TTA) + the on-disk bundle
#     (19-models-manifest.sha256; 19-weights-provenance.json).
#
# crop_cascade parts-ordering convention: in a crop spec, parts[0] names the
# CROP-MODEL bundle (its labelmap yields the crop mask) and parts[1:] are the
# post-crop model(s). The same convention will hold for the catalog's other
# crop+multi-part tasks (e.g. headneck_muscles).
#
# CROP SEMANTICS (18-RESEARCH §Critical Correction, verified in TS 2.18.0
# source + 2 live runs): crop.addon units are MM, applied at NATIVE input
# resolution with truncated mm->voxel conversion (cropping.py crop_to_mask:
# (addon / native_zooms).astype(int); python_api.py:411 [20,20,20] default).
# The crop is NOT applied at task resolution; the task-res resample
# (spec.resample) runs AFTER the crop. The ROADMAP's "task-resolution crop"
# parenthetical is disproven (corrected at phase closeout).
# ---------------------------------------------------------------------------
TASK_REGISTRY: Dict[str, TaskSpec] = {
    "total": TaskSpec(
        task_id=(291, 292, 293, 294, 295),  # organs/vertebrae/cardiac/muscles/ribs nnUNet ids
        family="multi_part",
        parts=(
            PartSpec(name="organs", label_offset=0, config_name="3d_fullres", max_local_label=24),
            PartSpec(name="vertebrae", label_offset=24, config_name="3d_fullres", max_local_label=26),
            PartSpec(name="cardiac", label_offset=50, config_name="3d_fullres", max_local_label=18),
            PartSpec(name="muscles", label_offset=68, config_name="3d_fullres", max_local_label=23),
            PartSpec(name="ribs", label_offset=91, config_name="3d_fullres", max_local_label=26),
        ),
        crop=None,
        resample=1.5,
        target_spacing=1.5,
        resample_order=3,
        trainer="nnUNetTrainer",
        tta=False,
        snomed="ai_segment_descriptions",
        snomed_module="ai_segment_descriptions",
        labels="volume_labels",
        output_mode="seg_sr",
    ),
    "liver_segments": TaskSpec(
        task_id=570,
        family="crop_cascade",
        parts=(
            # parts[0] = crop model (117-class 6mm total; liver == local label 5)
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            # parts[1] = post-crop main model (8 Couinaud segments)
            PartSpec(name="ct_liver_segments", label_offset=0, config_name="3d_fullres", max_local_label=8),
        ),
        # addon (20, 20, 20) = MM at native input resolution, truncated
        # mm->voxel (see CROP SEMANTICS block above).
        crop=CropSpec(source=None, labels=("liver",), addon=(20, 20, 20)),
        resample=(0.8046879768371582, 0.8046879768371582, 1.5),  # TS config verbatim (task-res, after crop)
        target_spacing=6.0,  # crop-model input spacing (crop pre-stage)
        resample_order=1,  # TS CLI default; NOT the oracle's 3 (18-RESEARCH Pitfall 4)
        trainer="nnUNetTrainerNoMirroring",
        tta=False,
        snomed="liver_segment_descriptions",  # 8-entry 99COUINAUD table (lands in 18-02)
        snomed_module="ai_liver_segment_descriptions",
        labels={
            "background": 0,
            "cnd.lv.seg.1": 1,
            "cnd.lv.seg.2": 2,
            "cnd.lv.seg.3": 3,
            "cnd.lv.seg.4": 4,
            "cnd.lv.seg.5": 5,
            "cnd.lv.seg.6": 6,
            "cnd.lv.seg.7": 7,
            "cnd.lv.seg.8": 8,
        },  # inline name->id table (9 keys); resolved to 99COUINAUD descriptions in 18-02
        output_mode="seg_sr",
    ),
    "body": TaskSpec(
        task_id=299,
        family="single_model",
        parts=(PartSpec(name="body", label_offset=0, config_name="3d_fullres", max_local_label=2),),
        crop=None,
        resample=1.5,  # TS body default: scalar 1.5 iso (NOT the liver tuple)
        target_spacing=1.5,
        resample_order=1,  # TS CLI default (python_api resampling_order=1)
        tile_step_size=0.5,  # TS nnunet.py:568-572: 0.8 only for the total family
        trainer="nnUNetTrainer",
        tta=False,
        snomed="body_descriptions",
        snomed_module="ai_body_descriptions",
        labels={"background": 0, "body_trunc": 1, "body_extremities": 2},
        output_mode="seg_sr",
        # TS nnunet.py:686-695 (body task, model resolution, pre-back-resample):
        # keep the largest body_trunc blob; drop body_extremities blobs <= 50,000 mm3.
        postprocess=(
            ("keep_largest_blob", "body_trunc"),
            ("remove_small_blobs", "body_extremities", 50000.0),
        ),
    ),
    "total_v3": TaskSpec(
        task_id=(831, 832, 833, 834, 835),
        family="multi_part",
        parts=(
            PartSpec(name="organs", label_offset=0, config_name="3d_fullres", max_local_label=24),
            PartSpec(name="vertebrae", label_offset=24, config_name="3d_fullres", max_local_label=26),
            PartSpec(name="cardiac", label_offset=50, config_name="3d_fullres", max_local_label=18),
            PartSpec(name="muscles", label_offset=68, config_name="3d_fullres", max_local_label=23),
            PartSpec(name="ribs", label_offset=91, config_name="3d_fullres", max_local_label=26),
        ),
        crop=None,
        resample=1.5,
        target_spacing=1.5,
        resample_order=1,
        tile_step_size=0.8,
        trainer="nnUNetTrainerNoMirroring",
        tta=False,
        snomed="total_v3_descriptions",  # 22-02: SNOMED table landed in Phase 22 (22-02)
        snomed_module="ai_total_v3_descriptions",
        labels={
            "background": 0,
            "spleen": 1,
            "kidney_right": 2,
            "kidney_left": 3,
            "gallbladder": 4,
            "liver": 5,
            "stomach": 6,
            "pancreas": 7,
            "adrenal_gland_right": 8,
            "adrenal_gland_left": 9,
            "lung_upper_lobe_left": 10,
            "lung_lower_lobe_left": 11,
            "lung_upper_lobe_right": 12,
            "lung_middle_lobe_right": 13,
            "lung_lower_lobe_right": 14,
            "esophagus": 15,
            "trachea": 16,
            "thyroid_gland": 17,
            "small_bowel": 18,
            "duodenum": 19,
            "colon": 20,
            "urinary_bladder": 21,
            "prostate": 22,
            "kidney_cyst_left": 23,
            "kidney_cyst_right": 24,
            "sacrum": 25,
            "vertebrae_L6": 26,
            "vertebrae_L5": 27,
            "vertebrae_L4": 28,
            "vertebrae_L3": 29,
            "vertebrae_L2": 30,
            "vertebrae_L1": 31,
            "vertebrae_T12": 32,
            "vertebrae_T11": 33,
            "vertebrae_T10": 34,
            "vertebrae_T9": 35,
            "vertebrae_T8": 36,
            "vertebrae_T7": 37,
            "vertebrae_T6": 38,
            "vertebrae_T5": 39,
            "vertebrae_T4": 40,
            "vertebrae_T3": 41,
            "vertebrae_T2": 42,
            "vertebrae_T1": 43,
            "vertebrae_C7": 44,
            "vertebrae_C6": 45,
            "vertebrae_C5": 46,
            "vertebrae_C4": 47,
            "vertebrae_C3": 48,
            "vertebrae_C2": 49,
            "vertebrae_C1": 50,
            "heart": 51,
            "aorta": 52,
            "pulmonary_vein": 53,
            "brachiocephalic_trunk": 54,
            "subclavian_artery_right": 55,
            "subclavian_artery_left": 56,
            "common_carotid_artery_right": 57,
            "common_carotid_artery_left": 58,
            "brachiocephalic_vein_left": 59,
            "brachiocephalic_vein_right": 60,
            "atrial_appendage_left": 61,
            "superior_vena_cava": 62,
            "inferior_vena_cava": 63,
            "portal_vein_and_splenic_vein": 64,
            "iliac_artery_left": 65,
            "iliac_artery_right": 66,
            "iliac_vena_left": 67,
            "iliac_vena_right": 68,
            "humerus_left": 69,
            "humerus_right": 70,
            "scapula_left": 71,
            "scapula_right": 72,
            "clavicula_left": 73,
            "clavicula_right": 74,
            "femur_left": 75,
            "femur_right": 76,
            "hip_left": 77,
            "hip_right": 78,
            "spinal_cord": 79,
            "gluteus_maximus_left": 80,
            "gluteus_maximus_right": 81,
            "gluteus_medius_left": 82,
            "gluteus_medius_right": 83,
            "gluteus_minimus_left": 84,
            "gluteus_minimus_right": 85,
            "autochthon_left": 86,
            "autochthon_right": 87,
            "iliopsoas_left": 88,
            "iliopsoas_right": 89,
            "brain": 90,
            "skull": 91,
            "rib_left_1": 92,
            "rib_left_2": 93,
            "rib_left_3": 94,
            "rib_left_4": 95,
            "rib_left_5": 96,
            "rib_left_6": 97,
            "rib_left_7": 98,
            "rib_left_8": 99,
            "rib_left_9": 100,
            "rib_left_10": 101,
            "rib_left_11": 102,
            "rib_left_12": 103,
            "rib_right_1": 104,
            "rib_right_2": 105,
            "rib_right_3": 106,
            "rib_right_4": 107,
            "rib_right_5": 108,
            "rib_right_6": 109,
            "rib_right_7": 110,
            "rib_right_8": 111,
            "rib_right_9": 112,
            "rib_right_10": 113,
            "rib_right_11": 114,
            "rib_right_12": 115,
            "sternum": 116,
            "costal_cartilages": 117,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "total_highres_test": TaskSpec(
        task_id=957,
        family="single_model",
        parts=(PartSpec(name="total_highres_test", label_offset=0, config_name="3d_fullres_high", max_local_label=24),),
        crop=None,
        resample=(0.75, 0.75, 1.0),
        target_spacing=(0.75, 0.75, 1.0),
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainerNoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "spleen": 1,
            "kidney_right": 2,
            "kidney_left": 3,
            "gallbladder": 4,
            "liver": 5,
            "stomach": 6,
            "pancreas": 7,
            "adrenal_gland_right": 8,
            "adrenal_gland_left": 9,
            "lung_upper_lobe_left": 10,
            "lung_lower_lobe_left": 11,
            "lung_upper_lobe_right": 12,
            "lung_middle_lobe_right": 13,
            "lung_lower_lobe_right": 14,
            "esophagus": 15,
            "trachea": 16,
            "thyroid_gland": 17,
            "small_bowel": 18,
            "duodenum": 19,
            "colon": 20,
            "urinary_bladder": 21,
            "prostate": 22,
            "kidney_cyst_left": 23,
            "kidney_cyst_right": 24,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "lung_vessels": TaskSpec(
        task_id=117,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_3mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="lung_vessels", label_offset=0, config_name="3d_fullres", max_local_label=4),
        ),
        crop=CropSpec(
            source=None,
            labels=(
                "lung_upper_lobe_left",
                "lung_lower_lobe_left",
                "lung_upper_lobe_right",
                "lung_middle_lobe_right",
                "lung_lower_lobe_right",
            ),
            addon=(20, 20, 20),
        ),
        resample=(0.703125, 0.703125, 1.0),
        target_spacing=3.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainerSkeletonRecall",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "lung_airways": 1, "lung_airways_wall": 2, "lung_arteries": 3, "lung_veins": 4},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=True,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "lung_vessels_LEGACY": TaskSpec(
        task_id=258,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="lung_vessels_LEGACY", label_offset=0, config_name="3d_fullres", max_local_label=2),
        ),
        crop=CropSpec(
            source=None,
            labels=(
                "lung_upper_lobe_left",
                "lung_lower_lobe_left",
                "lung_upper_lobe_right",
                "lung_middle_lobe_right",
                "lung_lower_lobe_right",
            ),
            addon=(20, 20, 20),
        ),
        resample=None,
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "lung_vessels": 1, "lung_trachea_bronchia": 2},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "cerebral_bleed": TaskSpec(
        task_id=150,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="cerebral_bleed", label_offset=0, config_name="3d_fullres", max_local_label=1),
        ),
        crop=CropSpec(source=None, labels=("brain",), addon=(20, 20, 20)),
        resample=None,
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "intracerebral_hemorrhage": 1},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "hip_implant": TaskSpec(
        task_id=260,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="hip_implant", label_offset=0, config_name="3d_fullres", max_local_label=1),
        ),
        crop=CropSpec(
            source=None,
            labels=("femur_left", "femur_right", "hip_left", "hip_right"),
            addon=(20, 20, 20),
        ),
        resample=None,
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "hip_implant": 1},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "pleural_pericard_effusion": TaskSpec(
        task_id=315,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="pleural_pericard_effusion", label_offset=0, config_name="3d_fullres", max_local_label=3),
        ),
        crop=CropSpec(
            source=None,
            labels=(
                "lung_upper_lobe_left",
                "lung_lower_lobe_left",
                "lung_upper_lobe_right",
                "lung_middle_lobe_right",
                "lung_lower_lobe_right",
            ),
            addon=(20, 20, 20),
        ),
        resample=None,
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer",
        tta=False,
        snomed="pleural_pericard_effusion_descriptions",  # 22-02: SNOMED table landed in Phase 22 (22-02)
        snomed_module="ai_pleural_pericard_effusion_descriptions",
        labels={"background": 0, "lung_pleural": 1, "pleural_effusion": 2, "pericardial_effusion": 3},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "liver_vessels": TaskSpec(
        task_id=8,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="liver_vessels", label_offset=0, config_name="3d_fullres", max_local_label=2),
        ),
        crop=CropSpec(source=None, labels=("liver",), addon=(20, 20, 20)),
        resample=None,
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "liver_vessels": 1, "liver_tumor": 2},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "head_glands_cavities": TaskSpec(
        task_id=775,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="head_glands_cavities", label_offset=0, config_name="3d_fullres_high", max_local_label=19),
        ),
        crop=CropSpec(source=None, labels=("skull",), addon=(20, 20, 20)),
        resample=(0.75, 0.75, 1.0),
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0_NoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "eye_left": 1,
            "eye_right": 2,
            "eye_lens_left": 3,
            "eye_lens_right": 4,
            "optic_nerve_left": 5,
            "optic_nerve_right": 6,
            "parotid_gland_left": 7,
            "parotid_gland_right": 8,
            "submandibular_gland_right": 9,
            "submandibular_gland_left": 10,
            "nasopharynx": 11,
            "oropharynx": 12,
            "hypopharynx": 13,
            "nasal_cavity_right": 14,
            "nasal_cavity_left": 15,
            "auditory_canal_right": 16,
            "auditory_canal_left": 17,
            "soft_palate": 18,
            "hard_palate": 19,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "headneck_bones_vessels": TaskSpec(
        task_id=776,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="headneck_bones_vessels", label_offset=0, config_name="3d_fullres_high", max_local_label=12),
        ),
        crop=CropSpec(
            source=None,
            labels=(
                "clavicula_left",
                "clavicula_right",
                "vertebrae_C1",
                "vertebrae_C5",
                "vertebrae_T1",
                "vertebrae_T4",
            ),
            addon=(20, 20, 20),
        ),
        resample=(0.75, 0.75, 1.0),
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0_NoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "larynx_air": 1,
            "thyroid_cartilage": 2,
            "hyoid": 3,
            "cricoid_cartilage": 4,
            "zygomatic_arch_right": 5,
            "zygomatic_arch_left": 6,
            "styloid_process_right": 7,
            "styloid_process_left": 8,
            "internal_carotid_artery_right": 9,
            "internal_carotid_artery_left": 10,
            "internal_jugular_vein_right": 11,
            "internal_jugular_vein_left": 12,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "head_muscles": TaskSpec(
        task_id=777,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="head_muscles", label_offset=0, config_name="3d_fullres_high", max_local_label=11),
        ),
        crop=CropSpec(source=None, labels=("skull",), addon=(20, 20, 20)),
        resample=(0.75, 0.75, 1.0),
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0_NoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "masseter_right": 1,
            "masseter_left": 2,
            "temporalis_right": 3,
            "temporalis_left": 4,
            "lateral_pterygoid_right": 5,
            "lateral_pterygoid_left": 6,
            "medial_pterygoid_right": 7,
            "medial_pterygoid_left": 8,
            "tongue": 9,
            "digastric_right": 10,
            "digastric_left": 11,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    # Phase-22 bundle-placement contract (D-21-2): place bundles at
    # models/headneck_muscles/{part1,part2}/ (TS weights
    # Dataset778/779_headneck_muscles_part{1,2}).
    "headneck_muscles": TaskSpec(
        task_id=(778, 779),
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="part1", label_offset=0, config_name="3d_fullres_high", max_local_label=11),
            PartSpec(name="part2", label_offset=11, config_name="3d_fullres_high", max_local_label=12),
        ),
        crop=CropSpec(
            source=None,
            labels=(
                "clavicula_left",
                "clavicula_right",
                "vertebrae_C1",
                "vertebrae_C5",
                "vertebrae_T1",
                "vertebrae_T4",
            ),
            addon=(20, 20, 20),
        ),
        resample=(0.75, 0.75, 1.0),
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0_NoMirroring",
        tta=False,
        snomed="headneck_muscles_descriptions",  # 22-02: SNOMED table landed in Phase 22 (22-02)
        snomed_module="ai_headneck_muscles_descriptions",
        labels={
            "background": 0,
            "sternocleidomastoid_right": 1,
            "sternocleidomastoid_left": 2,
            "superior_pharyngeal_constrictor": 3,
            "middle_pharyngeal_constrictor": 4,
            "inferior_pharyngeal_constrictor": 5,
            "trapezius_right": 6,
            "trapezius_left": 7,
            "platysma_right": 8,
            "platysma_left": 9,
            "levator_scapulae_right": 10,
            "levator_scapulae_left": 11,
            "anterior_scalene_right": 12,
            "anterior_scalene_left": 13,
            "middle_scalene_right": 14,
            "middle_scalene_left": 15,
            "posterior_scalene_right": 16,
            "posterior_scalene_left": 17,
            "sterno_thyroid_right": 18,
            "sterno_thyroid_left": 19,
            "thyrohyoid_right": 20,
            "thyrohyoid_left": 21,
            "prevertebral_right": 22,
            "prevertebral_left": 23,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "oculomotor_muscles": TaskSpec(
        task_id=351,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="oculomotor_muscles", label_offset=0, config_name="3d_fullres", max_local_label=19),
        ),
        crop=CropSpec(source=None, labels=("skull",), addon=(20, 20, 20)),
        resample=(0.47251562774181366, 0.47251562774181366, 0.8500002026557922),
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0_NoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "skull": 1,
            "eyeball_right": 2,
            "lateral_rectus_muscle_right": 3,
            "superior_oblique_muscle_right": 4,
            "levator_palpebrae_superioris_right": 5,
            "superior_rectus_muscle_right": 6,
            "medial_rectus_muscle_left": 7,
            "inferior_oblique_muscle_right": 8,
            "inferior_rectus_muscle_right": 9,
            "optic_nerve_left": 10,
            "eyeball_left": 11,
            "lateral_rectus_muscle_left": 12,
            "superior_oblique_muscle_left": 13,
            "levator_palpebrae_superioris_left": 14,
            "superior_rectus_muscle_left": 15,
            "medial_rectus_muscle_right": 16,
            "inferior_oblique_muscle_left": 17,
            "inferior_rectus_muscle_left": 18,
            "optic_nerve_right": 19,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "lung_nodules": TaskSpec(
        task_id=913,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="lung_nodules", label_offset=0, config_name="3d_fullres", max_local_label=2),
        ),
        crop=CropSpec(
            source=None,
            labels=(
                "lung_upper_lobe_left",
                "lung_lower_lobe_left",
                "lung_upper_lobe_right",
                "lung_middle_lobe_right",
                "lung_lower_lobe_right",
            ),
            addon=(20, 20, 20),
        ),
        resample=(1.5, 1.5, 1.5),
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_MOSAIC_1k_QuarterLR_NoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "lung": 1, "lung_nodules": 2},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "kidney_cysts": TaskSpec(
        task_id=789,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="kidney_cysts", label_offset=0, config_name="3d_fullres", max_local_label=2),
        ),
        crop=CropSpec(
            source=None,
            labels=("kidney_left", "kidney_right", "liver", "spleen", "colon"),
            addon=(20, 20, 20),
        ),
        resample=(1.5, 1.5, 1.5),
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0_NoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "kidney_cyst_left": 1, "kidney_cyst_right": 2},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "breasts": TaskSpec(
        task_id=527,
        family="single_model",
        parts=(PartSpec(name="breasts", label_offset=0, config_name="3d_fullres", max_local_label=1),),
        crop=None,
        resample=(1.5, 1.5, 1.5),
        target_spacing=(1.5, 1.5, 1.5),
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0_NoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "breast": 1},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "ventricle_parts": TaskSpec(
        task_id=552,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="ventricle_parts", label_offset=0, config_name="3d_fullres", max_local_label=12),
        ),
        crop=CropSpec(source=None, labels=("brain",), addon=(20, 20, 20)),
        resample=(0.4384765625, 0.4345703125, 1.0),
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainerNoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "ventricle_frontal_horn_left": 1,
            "ventricle_occipital_horn_left": 2,
            "ventricle_body_left": 3,
            "ventricle_temporal_horn_left": 4,
            "ventricle_trigone_left": 5,
            "ventricle_frontal_horn_right": 6,
            "ventricle_occipital_horn_right": 7,
            "ventricle_body_right": 8,
            "ventricle_temporal_horn_right": 9,
            "ventricle_trigone_right": 10,
            "third_ventricle": 11,
            "fourth_ventricle": 12,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "liver_lesions": TaskSpec(
        task_id=591,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_3mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="liver_lesions", label_offset=0, config_name="3d_fullres_high", max_local_label=1),
        ),
        crop=CropSpec(source=None, labels=("liver",), addon=(20, 20, 20)),
        resample=(0.75, 0.75, 1.0),
        target_spacing=3.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "liver_lesions": 1},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=True,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "craniofacial_structures": TaskSpec(
        task_id=115,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="craniofacial_structures", label_offset=0, config_name="3d_fullres", max_local_label=7),
        ),
        crop=CropSpec(source=None, labels=("skull",), addon=(20, 20, 20)),
        resample=(0.5, 0.5, 0.5),
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0_NoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "mandible": 1,
            "teeth_lower": 2,
            "skull": 3,
            "head": 4,
            "sinus_maxillary": 5,
            "sinus_frontal": 6,
            "teeth_upper": 7,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "abdominal_muscles": TaskSpec(
        task_id=952,
        family="crop_cascade",
        parts=(
            PartSpec(name="body", label_offset=0, config_name="3d_fullres", max_local_label=2),
            PartSpec(name="abdominal_muscles", label_offset=0, config_name="3d_fullres_high", max_local_label=22),
        ),
        crop=CropSpec(source=None, labels=("body_trunc",), addon=(20, 20, 20)),
        resample=(0.75, 0.75, 1),
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0_NoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "pectoralis_major_right": 1,
            "pectoralis_major_left": 2,
            "rectus_abdominis_right": 3,
            "rectus_abdominis_left": 4,
            "serratus_anterior_right": 5,
            "serratus_anterior_left": 6,
            "latissimus_dorsi_right": 7,
            "latissimus_dorsi_left": 8,
            "trapezius_right": 9,
            "trapezius_left": 10,
            "external_oblique_right": 11,
            "external_oblique_left": 12,
            "internal_oblique_right": 13,
            "internal_oblique_left": 14,
            "erector_spinae_right": 15,
            "erector_spinae_left": 16,
            "transversospinalis_right": 17,
            "transversospinalis_left": 18,
            "psoas_major_right": 19,
            "psoas_major_left": 20,
            "quadratus_lumborum_right": 21,
            "quadratus_lumborum_left": 22,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "teeth": TaskSpec(
        task_id=113,
        family="crop_cascade",
        parts=(
            PartSpec(name="craniofacial_structures", label_offset=0, config_name="3d_fullres", max_local_label=7),
            PartSpec(name="teeth", label_offset=0, config_name="3d_lowres_high", max_local_label=77),
        ),
        crop=CropSpec(
            source="craniofacial_structures",
            labels=("teeth_lower", "teeth_upper"),
            addon=(10, 10, 10),
        ),
        resample=(0.5, 0.5, 0.5),
        target_spacing=0.5,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_onlyMirror01",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "lower_jawbone": 1,
            "upper_jawbone": 2,
            "left_inferior_alveolar_canal": 3,
            "right_inferior_alveolar_canal": 4,
            "left_maxillary_sinus": 5,
            "right_maxillary_sinus": 6,
            "pharynx": 7,
            "bridge": 8,
            "crown": 9,
            "implant": 10,
            "upper_right_central_incisor_fdi11": 11,
            "upper_right_lateral_incisor_fdi12": 12,
            "upper_right_canine_fdi13": 13,
            "upper_right_first_premolar_fdi14": 14,
            "upper_right_second_premolar_fdi15": 15,
            "upper_right_first_molar_fdi16": 16,
            "upper_right_second_molar_fdi17": 17,
            "upper_right_third_molar_fdi18": 18,
            "upper_left_central_incisor_fdi21": 19,
            "upper_left_lateral_incisor_fdi22": 20,
            "upper_left_canine_fdi23": 21,
            "upper_left_first_premolar_fdi24": 22,
            "upper_left_second_premolar_fdi25": 23,
            "upper_left_first_molar_fdi26": 24,
            "upper_left_second_molar_fdi27": 25,
            "upper_left_third_molar_fdi28": 26,
            "lower_left_central_incisor_fdi31": 27,
            "lower_left_lateral_incisor_fdi32": 28,
            "lower_left_canine_fdi33": 29,
            "lower_left_first_premolar_fdi34": 30,
            "lower_left_second_premolar_fdi35": 31,
            "lower_left_first_molar_fdi36": 32,
            "lower_left_second_molar_fdi37": 33,
            "lower_left_third_molar_fdi38": 34,
            "lower_right_central_incisor_fdi41": 35,
            "lower_right_lateral_incisor_fdi42": 36,
            "lower_right_canine_fdi43": 37,
            "lower_right_first_premolar_fdi44": 38,
            "lower_right_second_premolar_fdi45": 39,
            "lower_right_first_molar_fdi46": 40,
            "lower_right_second_molar_fdi47": 41,
            "lower_right_third_molar_fdi48": 42,
            "left_mandibular_incisive_canal_fdi103": 43,
            "right_mandibular_incisive_canal_fdi104": 44,
            "lingual_canal": 45,
            "upper_right_central_incisor_pulp_fdi111": 46,
            "upper_right_lateral_incisor_pulp_fdi112": 47,
            "upper_right_canine_pulp_fdi113": 48,
            "upper_right_first_premolar_pulp_fdi114": 49,
            "upper_right_second_premolar_pulp_fdi115": 50,
            "upper_right_first_molar_pulp_fdi116": 51,
            "upper_right_second_molar_pulp_fdi117": 52,
            "upper_right_third_molar_pulp_fdi118": 53,
            "upper_left_central_incisor_pulp_fdi121": 54,
            "upper_left_lateral_incisor_pulp_fdi122": 55,
            "upper_left_canine_pulp_fdi123": 56,
            "upper_left_first_premolar_pulp_fdi124": 57,
            "upper_left_second_premolar_pulp_fdi125": 58,
            "upper_left_first_molar_pulp_fdi126": 59,
            "upper_left_second_molar_pulp_fdi127": 60,
            "upper_left_third_molar_pulp_fdi128": 61,
            "lower_left_central_incisor_pulp_fdi131": 62,
            "lower_left_lateral_incisor_pulp_fdi132": 63,
            "lower_left_canine_pulp_fdi133": 64,
            "lower_left_first_premolar_pulp_fdi134": 65,
            "lower_left_second_premolar_pulp_fdi135": 66,
            "lower_left_first_molar_pulp_fdi136": 67,
            "lower_left_second_molar_pulp_fdi137": 68,
            "lower_left_third_molar_pulp_fdi138": 69,
            "lower_right_central_incisor_pulp_fdi141": 70,
            "lower_right_lateral_incisor_pulp_fdi142": 71,
            "lower_right_canine_pulp_fdi143": 72,
            "lower_right_first_premolar_pulp_fdi144": 73,
            "lower_right_second_premolar_pulp_fdi145": 74,
            "lower_right_first_molar_pulp_fdi146": 75,
            "lower_right_second_molar_pulp_fdi147": 76,
            "lower_right_third_molar_pulp_fdi148": 77,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "trunk_cavities": TaskSpec(
        task_id=343,
        family="single_model",
        parts=(PartSpec(name="trunk_cavities", label_offset=0, config_name="3d_fullres", max_local_label=4),),
        crop=None,
        resample=(1.5, 1.5, 1.5),
        target_spacing=(1.5, 1.5, 1.5),
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer",
        tta=False,
        snomed="trunk_cavities_descriptions",  # 22-02: SNOMED table landed in Phase 22 (22-02)
        snomed_module="ai_trunk_cavities_descriptions",
        labels={"background": 0, "abdominal_cavity": 1, "thoracic_cavity": 2, "pericardium": 3, "mediastinum": 4},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "vertebrae_body": TaskSpec(
        task_id=305,
        family="single_model",
        parts=(PartSpec(name="vertebrae_body", label_offset=0, config_name="3d_fullres", max_local_label=2),),
        crop=None,
        resample=1.5,
        target_spacing=1.5,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "vertebrae_body": 1, "intervertebral_discs": 2},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "vertebrae_pp": TaskSpec(
        task_id=803,
        family="single_model",
        parts=(PartSpec(name="vertebrae_pp", label_offset=0, config_name="3d_fullres", max_local_label=24),),
        crop=None,
        resample=1.5,
        target_spacing=1.5,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainerNoMirroring",
        tta=False,
        snomed="vertebrae_pp_descriptions",  # 22-02: SNOMED table landed in Phase 22 (22-02)
        snomed_module="ai_vertebrae_pp_descriptions",
        labels={
            "background": 0,
            "vertebrae_C1": 1,
            "vertebrae_C2": 2,
            "vertebrae_C3": 3,
            "vertebrae_C4": 4,
            "vertebrae_C5": 5,
            "vertebrae_C6": 6,
            "vertebrae_C7": 7,
            "vertebrae_T1": 8,
            "vertebrae_T2": 9,
            "vertebrae_T3": 10,
            "vertebrae_T4": 11,
            "vertebrae_T5": 12,
            "vertebrae_T6": 13,
            "vertebrae_T7": 14,
            "vertebrae_T8": 15,
            "vertebrae_T9": 16,
            "vertebrae_T10": 17,
            "vertebrae_T11": 18,
            "vertebrae_T12": 19,
            "vertebrae_L1": 20,
            "vertebrae_L2": 21,
            "vertebrae_L3": 22,
            "vertebrae_L4": 23,
            "vertebrae_L5": 24,
        },
        output_mode="seg_sr",
        # 22-09: TS 2.18 nnunet.py:693-696 applies postprocess_vertebrae_pp
        # (3 mm per-label dilation into background + touching-labels
        # component split/relabel, min_size 100 mm3) at model resolution,
        # pre-back-resample. Root cause of the Class A gap — see
        # 22-class-a-diagnostics.md (full pp reproduces the pinned refs at
        # 1.0000 per-label IoU on all 3 Phase-22 studies).
        postprocess=(("dilate_labels", 3.0, 100.0),),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "vertebrae_pp_refined": TaskSpec(
        task_id=803,
        family="single_model",
        parts=(PartSpec(name="vertebrae_pp_refined", label_offset=0, config_name="3d_fullres", max_local_label=24),),
        crop=None,
        resample=1.5,
        target_spacing=1.5,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainerNoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "vertebrae_C1": 1,
            "vertebrae_C2": 2,
            "vertebrae_C3": 3,
            "vertebrae_C4": 4,
            "vertebrae_C5": 5,
            "vertebrae_C6": 6,
            "vertebrae_C7": 7,
            "vertebrae_T1": 8,
            "vertebrae_T2": 9,
            "vertebrae_T3": 10,
            "vertebrae_T4": 11,
            "vertebrae_T5": 12,
            "vertebrae_T6": 13,
            "vertebrae_T7": 14,
            "vertebrae_T8": 15,
            "vertebrae_T9": 16,
            "vertebrae_T10": 17,
            "vertebrae_T11": 18,
            "vertebrae_T12": 19,
            "vertebrae_L1": 20,
            "vertebrae_L2": 21,
            "vertebrae_L3": 22,
            "vertebrae_L4": 23,
            "vertebrae_L5": 24,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "heartchambers_highres": TaskSpec(
        task_id=301,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_3mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="heartchambers_highres", label_offset=0, config_name="3d_fullres", max_local_label=7),
        ),
        crop=CropSpec(source=None, labels=("heart",), addon=(20, 20, 20)),
        resample=None,
        target_spacing=3.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "heart_myocardium": 1,
            "heart_atrium_left": 2,
            "heart_ventricle_left": 3,
            "heart_atrium_right": 4,
            "heart_ventricle_right": 5,
            "aorta": 6,
            "pulmonary_artery": 7,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=True,
        remove_outside=("heart", "aorta", "inferior_vena_cava"),
        remove_outside_dilation=10.0,
        licensed=True,
    ),
    "appendicular_bones": TaskSpec(
        task_id=304,
        family="single_model",
        parts=(PartSpec(name="appendicular_bones", label_offset=0, config_name="3d_fullres", max_local_label=11),),
        crop=None,
        resample=1.5,
        target_spacing=1.5,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainerNoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "patella": 1,
            "tibia": 2,
            "fibula": 3,
            "tarsal": 4,
            "metatarsal": 5,
            "phalanges_feet": 6,
            "ulna": 7,
            "radius": 8,
            "carpal": 9,
            "metacarpal": 10,
            "phalanges_hand": 11,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=True,
    ),
    "tissue_types": TaskSpec(
        task_id=481,
        family="single_model",
        parts=(PartSpec(name="tissue_types", label_offset=0, config_name="3d_fullres", max_local_label=3),),
        crop=None,
        resample=1.5,
        target_spacing=1.5,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "subcutaneous_fat": 1, "torso_fat": 2, "skeletal_muscle": 3},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=True,
    ),
    "tissue_4_types": TaskSpec(
        task_id=485,
        family="single_model",
        parts=(PartSpec(name="tissue_4_types", label_offset=0, config_name="3d_fullres", max_local_label=4),),
        crop=None,
        resample=1.5,
        target_spacing=1.5,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "subcutaneous_fat": 1, "torso_fat": 2, "skeletal_muscle": 3, "intermuscular_fat": 4},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=True,
    ),
    "face": TaskSpec(
        task_id=303,
        family="single_model",
        parts=(PartSpec(name="face", label_offset=0, config_name="3d_fullres", max_local_label=1),),
        crop=None,
        resample=1.5,
        target_spacing=1.5,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainerNoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "face": 1},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=True,
    ),
    "brain_structures": TaskSpec(
        task_id=409,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="brain_structures", label_offset=0, config_name="3d_fullres_high", max_local_label=16),
        ),
        crop=CropSpec(source=None, labels=("brain",), addon=(20, 20, 20)),
        resample=(0.5, 0.5, 1.0),
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "brainstem": 1,
            "subarachnoid_space": 2,
            "venous_sinuses": 3,
            "septum_pellucidum": 4,
            "cerebellum": 5,
            "caudate_nucleus": 6,
            "lentiform_nucleus": 7,
            "insular_cortex": 8,
            "internal_capsule": 9,
            "ventricle": 10,
            "central_sulcus": 11,
            "frontal_lobe": 12,
            "parietal_lobe": 13,
            "occipital_lobe": 14,
            "temporal_lobe": 15,
            "thalamus": 16,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=True,
    ),
    "thigh_shoulder_muscles": TaskSpec(
        task_id=857,
        family="single_model",
        parts=(PartSpec(name="thigh_shoulder_muscles", label_offset=0, config_name="3d_fullres", max_local_label=18),),
        crop=None,
        resample=1.5,
        target_spacing=1.5,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_2000epochs_NoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "quadriceps_femoris_left": 1,
            "quadriceps_femoris_right": 2,
            "thigh_medial_compartment_left": 3,
            "thigh_medial_compartment_right": 4,
            "thigh_posterior_compartment_left": 5,
            "thigh_posterior_compartment_right": 6,
            "sartorius_left": 7,
            "sartorius_right": 8,
            "deltoid": 9,
            "supraspinatus": 10,
            "infraspinatus": 11,
            "subscapularis": 12,
            "coracobrachial": 13,
            "trapezius": 14,
            "pectoralis_minor": 15,
            "serratus_anterior": 16,
            "teres_major": 17,
            "triceps_brachii": 18,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=True,
    ),
    "coronary_arteries": TaskSpec(
        task_id=509,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="coronary_arteries", label_offset=0, config_name="3d_fullres_high", max_local_label=1),
        ),
        crop=CropSpec(source=None, labels=("heart",), addon=(20, 20, 20)),
        resample=(0.7, 0.7, 0.7),
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainerSkeletonRecall",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "coronary_arteries": 1},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=True,
    ),
    "coronary_arteries_LEGACY": TaskSpec(
        task_id=507,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="coronary_arteries_LEGACY", label_offset=0, config_name="3d_fullres_high", max_local_label=1),
        ),
        crop=CropSpec(source=None, labels=("heart",), addon=(20, 20, 20)),
        resample=(0.7, 0.7, 0.7),
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0_NoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "coronary_arteries": 1},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=True,
    ),
    "aortic_sinuses": TaskSpec(
        task_id=920,
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="aortic_sinuses", label_offset=0, config_name="3d_fullres_high", max_local_label=4),
        ),
        crop=CropSpec(source=None, labels=("heart",), addon=(20, 20, 20)),
        resample=(0.7, 0.7, 0.7),
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0_NoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "left_ventricular_outflow_tract": 1,
            "right_coronary_cusp": 2,
            "left_coronary_cusp": 3,
            "non_coronary_cusp": 4,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=True,
    ),
    "renal_arteries": TaskSpec(
        task_id=710,
        family="single_model",
        parts=(PartSpec(name="renal_arteries", label_offset=0, config_name="3d_fullres", max_local_label=3),),
        crop=None,
        resample=1.5,
        target_spacing=1.5,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0_NoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "celiac_trunk": 1, "superior_mesenteric_artery": 2, "renal_arteries": 3},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=True,
    ),
    "aorta_annulus": TaskSpec(
        task_id=713,
        family="single_model",
        parts=(PartSpec(name="aorta_annulus", label_offset=0, config_name="3d_fullres_high", max_local_label=2),),
        crop=None,
        resample=(0.8, 0.8, 0.8),
        target_spacing=(0.8, 0.8, 0.8),
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "annulus_proper": 1, "sinotubular_junction": 2},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0, 1, 2, 3, 4),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=True,
    ),
    "aortic_dissection": TaskSpec(
        task_id=716,
        family="single_model",
        parts=(PartSpec(name="aortic_dissection", label_offset=0, config_name="3d_fullres_high", max_local_label=2),),
        crop=None,
        resample=(0.8, 0.8, 0.8),
        target_spacing=(0.8, 0.8, 0.8),
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer_DASegOrd0_NoMirroring",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "aorta_true_lumen": 1, "aorta_false_lumen": 2},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0, 1, 2, 3, 4),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=True,
    ),
    "pulmonary_artery_landmarks": TaskSpec(
        task_id=514,
        family="single_model",
        parts=(
            PartSpec(name="pulmonary_artery_landmarks", label_offset=0, config_name="3d_fullres", max_local_label=7),
        ),
        crop=None,
        resample=(0.7802734375, 0.7802734375, 1.0),
        target_spacing=(0.7802734375, 0.7802734375, 1.0),
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainer",
        tta=False,
        snomed="",
        snomed_module="",
        labels={
            "background": 0,
            "annulus": 1,
            "sinotubular_junction": 2,
            "pul_annulus": 3,
            "pul_sinotubular_junction": 4,
            "pul_bifurcation": 5,
            "pul_left_start": 6,
            "pul_right_start": 7,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0, 1, 2, 3, 4),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=True,
    ),
    "test": TaskSpec(
        task_id=(517,),
        family="crop_cascade",
        parts=(
            PartSpec(name="total_6mm", label_offset=0, config_name="3d_fullres", max_local_label=117),
            PartSpec(name="test", label_offset=0, config_name="3d_fullres", max_local_label=1),
        ),
        crop=CropSpec(
            source="body", labels=(), addon=(20, 20, 20)
        ),  # deprecated TS string-crop form ("body"), dev task
        resample=None,
        target_spacing=6.0,
        resample_order=1,
        tile_step_size=0.5,
        trainer="nnUNetTrainerV2",
        tta=False,
        snomed="",
        snomed_module="",
        labels={"background": 0, "carpal": 1},
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    # Phase-26 DEV layout-test tasks (26-01, CFG-01 enabler): single-part
    # organs bundles in the lowres and cascade_fullres layouts so the config
    # matrix cells are RUN-able (26-03/26-04 build the synthetic bundles from
    # the registry corpus per D-01; the cascade cell additionally needs
    # HOLOSCAN_SYNTHETIC_CASCADE=1 for the zero one-hot stub). Structured on
    # the "body" single_model entry; task_id=(291,) — organs is Dataset291
    # (first id of the "total" entry). Labels = the organs 24-label subset of
    # the total spec's volume_labels map (ids 1..24, label_offset 0).
    # Not in the 43-task TS catalog; the Phase 27 README will document them.
    "organs_lowres_test": TaskSpec(
        task_id=(291,),
        family="single_model",
        parts=(PartSpec(name="organs", label_offset=0, config_name="3d_lowres", max_local_label=24),),
        crop=None,
        resample=None,
        target_spacing=None,
        resample_order=3,
        tile_step_size=0.8,
        trainer="nnUNetTrainerNoMirroring",
        tta=False,
        snomed="organs_descriptions",
        snomed_module="ai_segment_descriptions",
        labels={
            "background": 0,
            "spleen": 1,
            "r.kidney": 2,
            "l.kidney": 3,
            "gallbladder": 4,
            "liver": 5,
            "stomach": 6,
            "pancreas": 7,
            "r.adrnl.glnd": 8,
            "l.adrnl.glnd": 9,
            "l.lng.up.lb": 10,
            "l.lng.low.lb": 11,
            "r.lng.up.lb": 12,
            "r.lng.mid.lb": 13,
            "r.lng.low.lb": 14,
            "esophagus": 15,
            "trachea": 16,
            "thyroid": 17,
            "small.bowel": 18,
            "duodenum": 19,
            "colon": 20,
            "urinry.blddr": 21,
            "prostate": 22,
            "l.kid.cyst": 23,
            "r.kid.cyst": 24,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
    "organs_cascade_test": TaskSpec(
        task_id=(291,),
        family="single_model",
        parts=(PartSpec(name="organs", label_offset=0, config_name="3d_cascade_fullres", max_local_label=24),),
        crop=None,
        resample=None,
        target_spacing=None,
        resample_order=3,
        tile_step_size=0.8,
        trainer="nnUNetTrainerNoMirroring",
        tta=False,
        snomed="organs_descriptions",
        snomed_module="ai_segment_descriptions",
        labels={
            "background": 0,
            "spleen": 1,
            "r.kidney": 2,
            "l.kidney": 3,
            "gallbladder": 4,
            "liver": 5,
            "stomach": 6,
            "pancreas": 7,
            "r.adrnl.glnd": 8,
            "l.adrnl.glnd": 9,
            "l.lng.up.lb": 10,
            "l.lng.low.lb": 11,
            "r.lng.up.lb": 12,
            "r.lng.mid.lb": 13,
            "r.lng.low.lb": 14,
            "esophagus": 15,
            "trachea": 16,
            "thyroid": 17,
            "small.bowel": 18,
            "duodenum": 19,
            "colon": 20,
            "urinry.blddr": 21,
            "prostate": 22,
            "l.kid.cyst": 23,
            "r.kid.cyst": 24,
        },
        output_mode="seg_sr",
        postprocess=(),
        folds=(0,),
        robust_crop=False,
        remove_outside=(),
        remove_outside_dilation=0.0,
        licensed=False,
    ),
}


def get_task_spec(name: str) -> TaskSpec:
    """Return the registry entry for ``name``; fail fast on an unknown task.

    Raises:
        ValueError: naming the unknown value and the sorted valid task set
            (no silent fallback — a bad HOLOSCAN_TASK must die before GPU work).
    """
    try:
        return TASK_REGISTRY[name]
    except KeyError:
        raise ValueError(f"unknown HOLOSCAN_TASK {name!r}; valid tasks: {sorted(TASK_REGISTRY)}") from None


# Topology construction (pure data; plans.py). Imported LAST so the names this
# module already defines (TaskSpec, PartSpec) exist before plans' dual-import of
# them runs. Plans is stdlib-only, so the headless-import rule still holds.
try:  # package-style import (my_app.*)
    from my_app.task_specs.plans import CROP_STAGES, TopologyPlan, build_topology, resolve_part
except ImportError:  # flat import (my_app dir on sys.path, as the app runner provides)
    from task_specs.plans import CROP_STAGES, TopologyPlan, build_topology, resolve_part
